---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mssql
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/lianalabs/apps/database/mssql/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
