# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: radarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:E0qbyZTPj6yQGkVb74K6/sg7304gfo0TGP3pqK9z8urD2Z+jGz/WNqCfgAw=,iv:yVwugLsqnoeChODoq0/72ko+AsMTMqFCfpV+TOMeX2o=,tag:8CkPM/5HCfcKUcd6jy/+Yg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdjZIM3BQTlJScC9yZXhV
        Vm9WdVdPUXN2ZEpKMVF4WGlwcUtFTDlqNzM4CklMUmRoZzF6K2Q2Yi82S1d5cHRG
        MllLSlR3Y0RMQW1welF0TDBDaWtvRXMKLS0tIDRRSGUyRVF4Y0QwS2J1RUFjeDZS
        d0NpL3dWRFFaZnY5ZGxvQUdKb0M3bzQKrsxU8yklK0OYUeJXnzYnOJGHBfJ4EeNT
        t46v+3RCiIVNdWO+epWhH1BpUI7ugXH/VistEPpln13pI7I9P7rcfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-10T04:19:08Z"
  mac: ENC[AES256_GCM,data:f7GXIR1DTXuVbIr75DeNAd192ngGjW+vkazubhL6R7P2itX2R/r6FOqhabIPced+8K9o94qhGcK7apxVQT7CNvP3f7fDlwec1SnWOhMdWQZX892SjluGfp2T7BDBL7DoRSClSaudtVN9Z/9J3NJeN+uFxJAvThjygULrOjCbEDI=,iv:Zk+1BrC8yQwfvpl6F7E7uxXe08Yn7aahy3IuCOmzq1Q=,tag:vLX610JvXG1uHJ7bxRxeCQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
