# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: radarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:XkW/YA9BNLykhXbjUgMh6y0T/LeEZv9aswXpLPfm3hDDZuIOi02xrMKFQ8s=,iv:tChWTpvFhe9QKfryTkdLBxrDeUZV+nMi5GqTRTfLiPs=,tag:NHZi8WRndIriZDwX066FKA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTFpmM05xZ3F0R0VqTDBU
        OGJoRzJPTHVrNUw1c2JqZWlzeDhYNE5Ja2dnCjUwZlpuQ1dkcGhnY0p3ZkNZV000
        RVc2ODhYcFZFSTNHMzBBNUo3M0g2RHcKLS0tIHhEdlFEbWN3eHhRVFRpNU1hOEYr
        djY2TkZPZVY0Q3BSQzhvVE1BVDBsQlUK/5XRuVofHjLBAoXff2PKiuK/mQKZXf05
        xXbElNkxDL+BZETZUCEZ+smQuSfyiEwtP12V+JCzpQM3loUu53DyqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-10T05:11:25Z"
  mac: ENC[AES256_GCM,data:M7+WgAGETcqwG5PHV4fKzDRF4MIFB6YwicclVgrcK5+Z0s6W4GxsC1iaoYYGFbjCge8a+7zdkcfwfZTMne460FZPOFYrwzZQD45dtrihMbMjBBXM3Yv6gkJiQjcOnmnSTQJDOMfGxoc01eXyg9DXPBtv13EcfbTlYVeV85MwOFM=,iv:oNmUIPbkSkIUbkjHvQ4/jrY0F01Yo6j6/32yStNthXg=,tag:Y2KqkLeEV090ibJsDAxjLg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
