# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: radarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:v/j9kdbh8MYfzELhxt5oESAc8Q8FXO+abCwEVGGnGjk=,iv:/2/siDtSQF7gJNvUJwVXpwB4BVWKCHJHc/I4Dd/juWk=,tag:AArqq/pai2JFOvQEplTLnA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb0t5VTJZRWNaYWg5S0VE
        dzA0bDN1VktyTjBuTDRzbVc3VGJkUnp1aDBJCjN4QUR0bDRXWm9RVUpiNFdyc2Ew
        K0xwZXVCYUFuamJSQTIrYmpReUZBWTAKLS0tICtwVUdyYXdzNldvOW1jUjZPZUhE
        amQxYzVXN2NGSzk5bklXRC9OL28zdVEKegrYZ5BA/GbWSmesO+yP0ZlG+MOj5DT7
        +6aZ6xqd2m9wVAk/hMPzz5ZSFEkuxLnPalju+jTeLgNrRCCmkWFpzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-10T15:45:28Z"
  mac: ENC[AES256_GCM,data:x8oxtzoqQHnAx9D7nGEu/ftinTl3BsshjbA2E8x1TwirCnhyuevJaMTmjXSP9pDyqktoz9smWgHxq8GcWQAzu9vUSKfjyM6q1y3p6qstMSx2Ky4+YlRLSjMnX2693/i0bAgvhAm1MyDTp8R2wORgf7kK6WRWUIDKvSp8BGXQb5U=,iv:IjSJooaV47cq4EjbQCidyQ2j3GYkQpKswSHW+qMXQrk=,tag:Cva95E39DXS5oxcEPW1uaA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
