# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: radarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:gxkN3E/5dL+7CGQM5l/uHBnVDdIdiwS5dYiEvKHTDCo=,iv:zLq1oASlPBZPvkdc4HE114HX2Ov0vIQiZQCB18LF5UE=,tag:x0wgzPCptgP3TStVq2Pauw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N1VON2wzSU1qS29JcWp2
        aHdSTnRJMWNVWnprMGJvd1pEQWVQU0k1K2lzCjM1Z0lHMTdwVmE5L2FhVjlMSHFU
        eDR2OWpnQXBOaXhjTTgxTFlwMzFsbkUKLS0tIFR1SXpBTFBTczY2eWcwVHpEZGpu
        SXh1UE1YUG5nRzZOTjA5dUdqWEJVaGsKdmozLDtCE+9EJ3YbTQSkf94GTP+D2mw6
        jfCoZGqYS499fPd9VBYbMEpDBhIwLbYZ5owzH7nytxuRzTIaSBC7XQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-16T01:27:11Z"
  mac: ENC[AES256_GCM,data:MRPVbf441EckTIBO1BII/yxcZB9NQNXju7JhjIyHFPYyxAHc9qAloWY0nIIeC+8N6EyF0vgE+jwWcbrp7PZTfI8FoMR2IGu2BY+E31oN7HflfgQmwSC0Jzku2wVs9qGgz82WP3sEf1vx9MHxItCyGkuKYt5NkzS5ZZ4HQptO+FU=,iv:P6ZxAJtlnYjtOXvCx76r3KfZsgNqzuy3xbn4V2DI12I=,tag:RZspwidojmmKlPFpA7ZWZw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
