# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: radarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:ljSxSCIrysdpD6XqyoGfarPqppjwicVHkdSxsJoPov4=,iv:L4lac0lhK3qO+XOMz4j8HYAIMvkXUKLVXyS+VEBeYpA=,tag:0jHhKVg7exrp6o7K39L/xQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bmZmcjVrc1g3SnJnSEZw
        cXZtM0xWTk1DVTZ1ejlXWmMwNzRacTZ1c1Z3CmdNa0pXMWhFd0pqdmJjaGIzVnNV
        R04zbHhpNERtdzdwM1Jwa0cyQi9hMjgKLS0tIHNSajJSQjlSekxHc01aaU1wZGlT
        bjEwUnZtYnJ4ZDI2RXdsMk5kR3hvaXMKmtlKZCSDWvON0QnSrCX9n1ZHFoeO0eue
        fefuj3z5VEJvCOPo/ee+/rJHxE4YZHgVhBF3jmrq/Bq4KJesuARJcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-10T05:47:36Z"
  mac: ENC[AES256_GCM,data:8OshZYgK3fGwBEA8ZKFs+whhmfTpTBCNO6lJQ491iRRCc09whurAHqimO92f+DfyZ3ZthvKgq8JdXFs5Rfi4UqPZg7ImhlSWfR7w1KShLUK41mdsZy+kDTPrdYzgDKl1ubH+Esd+ORa0p0oUs0CKN/4qkxg5zl3igmLfx5+r5Sg=,iv:njwFCWnXSRi0aeb/6pX17+L0bNMLVdB7o4AignvEKk4=,tag:afm4n8O5g/84/oOgx3i4XQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
