---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: lldap-secret
    template:
      engineVersion: v2
      data:
        # TODO: Finish this
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD }}"
        AUTHELIA_SESSION_SECRET:
        AUTHELIA_STORAGE_ENCRYPTION_KEY:
        AUTHELIA_STORAGE_POSTGRES_USERNAME:
        AUTHELIA_STORAGE_POSTGRES_PASSWORD:
        AUTHELIA_NOTIFIER_SMTP_ADDRESS:
        AUTHELIA_NOTIFIER_SMTP_USERNAME:
        AUTHELIA_NOTIFIER_SMTP_PASSWORD:
        GRAFANA_OAUTH_CLIENT_HASHED_SECRET:
        MINIFLUX_OAUTH_CLIENT_HASHED_SECRET:
        OIDC_JWKS_KEY:
        OIDC_JWKS_CERTIFICATE:
  data:
    - secretKey: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
      remoteRef:
        key:
