# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: miniflux-secret
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:aNIMq3s=,iv:H0y1eviUfbspd89s4irIzjUgiJlwn5ppww9jYnM8r2c=,tag:Vs+o/AQYMkNZ2taQFkjLQA==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:5kho75mEHvZ42B4uMgjICBWnBmzgFHXh+jTCiA==,iv:z/cx42x9pVDYAZSIitcu9EBHirvYAujjNs/AoU5IYuQ=,tag:s/MEOsj2HgWYRxPSnI7tJA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:gyhTxqQbzZU=,iv:lSOdq1ryg3WA1nWGQBM0F2iwY3PA6Z17W/OdNAzcEHI=,tag:RlRY7g09+NlT6hvquYD3VQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:IxmL18pMhgptP08Fhq4MIo2/DIim+ubGeM6dOA==,iv:fTOVVDg/ZUPZ63g8opVvkhZbKed1ippxkNzR+5jO/S4=,tag:u910HnXXEaZSqSZ2fIXhQw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:7vAPHPqN6ER13CzQnS+40p0tsRbWhdsqCccflCToOfH3/ljXLm5D2dIt2wFv6xQaWd3hAlesAzzKn/Rbivd3YAfdG8dRWxVFxkg68YtN+BsqtNu/chXuI7YD7Q==,iv:uYbt5wJusvWEPuMbC4b1l11IbyqkBcGk56Il4T6lF7c=,tag:Hw/ung+3m8lTbBcROmuyIg==,type:str]
  OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:iC1yz6kDr9MU5f6LpssMZqeNtorrXnxTLTfYsXk31v+Fyi/8eByb0HwusKd8ByFY1RWe/LixYTW9RgH2lPgVd8oMNyX0Wn8=,iv:xTWxj26fH/QmAenMzj9zGHOjjjvdrXkruwRvICvA+w8=,tag:UhqM0KbaZfsut7hKqv8g2A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZHF2WWlIUThCbXVjVHBN
        VU9uVWphYmVHOVVneW5tbExDWjB6NjhrYndRCnl4MW5Oc2JONWE3enFVZEdKNE9R
        OWg3VWYyd3VVQ29jTU5ISnNwVGVIQ2MKLS0tIEdEU3krb2FYaE9ycHdHTjhhdnA3
        cEgrYWZPeHA3QmFhQTVMVlJFdUVZODAKKkxfTEsV7mxFRU7ODttsGJHABZ8zdqz8
        JHYp0DGWKamQvDDDVG2P3/EmdkyBOHqZmNIj+GX09lKf0NRw4ecS0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T02:17:53Z"
  mac: ENC[AES256_GCM,data:kH/EiCAoa5fkA1xsr2m02D4CdI+PMzcOeM706+kjyLMjR5rFxMeY5eysHhDHzEwwY8gzzdhrIF/5loB5/shGAejpeUZ+YaN5ZLiLWx2C0MDOsUiEePfUr8Sq/+AZ8+i5t1jwHEPeowy+9dm0WPn6U4c7oUuQzFyV/sQJNARw9vQ=,iv:L6sbMAQZVs18MHJcpEOgbThUbJF5j/IZmad008t77Hg=,tag:tX3un6r3VDwicp+IrUUXxw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
