# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: radarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:4Y07nOSoTdfLLkBP+StLURv2RcCxpfhshP4gF4yiB68=,iv:Lj2PfTaRlEzjl5IxOTU8Yj5FFxuqQseCJJ1gTIIYDvw=,tag:qx06HVoR/Ac86P0a7kVTBg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSEJTdHlsRTlDcjhQQ28x
        MDVtQ2pNVjRHb0Mrb05obHpwb3ByenJhNGpjCnlsb3NsVk5hYlE4UTFJcmxGOCtn
        QjlDUXUzWHJCTVlrZFlUNWxWb0NpaU0KLS0tIDIxUXFmenh2QkppSDVwdkdHb3Fp
        a1k1UUJmWmJiTklxN25BNStYMndpNHMKAXNGAWWGwpl8plENURnr9rLLflN2azkZ
        Eq34skh5YbnZJjhffj5q7CqR6VO7Ary4DdUyF7ycjAELT61Ty+UPvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T02:17:54Z"
  mac: ENC[AES256_GCM,data:L5b5ipQGACVFf3zTbKXe+ew8bu/qb2sIv5J6xjkUd6Ef2V/60IB9c4yrwdx10P9CRn/saVvVjxrgF845oPWAkMIfkN5cz8bu0xK8qDGa+1PNHfdzUGCxbM2KckbXdvn1XITb/6YGCHjOUAF8zuRMAp+uoQJF7N8S3G5tRDckHX0=,iv:wJ6cK7LSoepRdCezjcsd3IYjON4eQ8FyH/j64wSsFtU=,tag:Rhk4GW7ZkK3AbJWJ0QlbUg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
