---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      qbittorrent:
        annotations:
          configmap.reloader.stakater.com/reload: qbittorrent-dnsdist
          secret.reloader.stakater.com/reload: qbittorrent-secret
        initContainers:
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-19
              tag: 1.9.7@sha256:6ed810f4d5da4585ccfc2667a794a78319ff2960a43266fc6a160c063d04e1ef
            restartPolicy: Always
          gluetun:
            dependsOn:
              - dnsdist
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: latest@sha256:aaaf6c7c108f7f7caae978499b4cb823a135324992ce7cea4acd405a29298141
            env:
              DOT: "off"
              DNS_ADDRESS: "127.0.0.2"
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              WIREGUARD_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: ${NODE_CIDR},${CLUSTER_CIDR},${SERVICE_CIDR}
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            resources:
              limits:
                squat.ai/tun: "1"
            restartPolicy: Always
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 501
          terminationGracePeriodSeconds: 120
        containers:
          qbittorrent:
            #nameOverride: qbittorrent
            image:
              repository: ghcr.io/liana64/qbittorrent-beta
              tag: 5.0.2@sha256:84961a7f137dc4d80460ca0bf4746477f751767579278ae0d4164dcb5cc735d5
            env:
              UMASK: "022"
              QBT_WEBUI_PORT: &port 8080
              QBT_BitTorrent__Session__MaxActiveDownloads: 10
              QBT_BitTorrent__Session__MaxActiveTorrents: 16384
              QBT_BitTorrent__Session__MaxActiveUploads: 50
              QBT_BitTorrent__Session__DefaultSavePath: "/data/r720xd-media/M Media/00-09 Archives/00 Downloads/00.00 Torrent Downloads"
              QBT_Application__MemoryWorkingSetLimit:
                valueFrom:
                  resourceFieldRef:
                    containerName: qbittorrent
                    resource: limits.memory
                    divisor: 1Mi
              QBT_Preferences__WebUI__Username:
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: QBITTORRENT_USER
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 150m
                memory: 2048Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          port-forward:
            image:
              repository: ghcr.io/bjw-s/gluetun-qb-port-sync
              tag: latest@sha256:ebabf8031406a29a1e642cb9eb83b96de9fc442daf3effc85b23047dde7acbd1
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      qbittorrent:
        controller: qbittorrent
        ports:
          http:
            port: *port
    ingress:
      qbittorrent:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_EXTERNAL_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/description: Torrent client
          gethomepage.dev/icon: qbittorrent
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: qbittorrent
                  port: http
        tls:
          - secretName: qbittorrent-tls
            hosts: [*host]
    persistence:
      config:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
          - path: /config
      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-forward:
              - path: /config
      nfs-media:
        type: nfs
        server: ${NFS_HOST}
        path: ${NFS_MEDIA}
        advancedMounts:
          qbittorrent:
            qbittorrent:
              - path: /data/r720xd-media
                readOnly: false
      dnsdist:
        type: configMap
        name: qbittorrent-dnsdist
        advancedMounts:
          qbittorrent:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true
