# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: qbittorrent-secret
stringData:
  QBITTORRENT_USER: ENC[AES256_GCM,data:b9w0PXY=,iv:edP33dgxorP/QMtQaTo4DkBp24fxWaiVN3iC9iy9VnY=,tag:brUA0mJ0uT6YYF6NGHITmQ==,type:str]
  QBITTORRENT_PASS: ENC[AES256_GCM,data:J/T6ytwqNEVMRsXUvUdSn22czK13L3Yf7Gs1Kg==,iv:DDl/xp/TSHsFnm2YdW42v5BJEBEv8efcipbUC74zbZ4=,tag:g1UF2V+nYXZwFhwQO0ndvA==,type:str]
  WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:AMtv/fA2EBhkGPWD/ls=,iv:gtA3tg7PwwcEiAiTBlwQa4MuWKG/mBQfkrS7+QFCWQg=,tag:H1bUKxTgxBNuDd5rKfAhRQ==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Ku/Cp9gqrH6HBwtC0FpGiYuMONCztMjJVH24Q4jIAD8WR4g2SsxkutsPXhQ=,iv:jC4KChiA05DalCM1+avJEKvlgawG6LEr28FozEWBNc8=,tag:FojIaxnzxSNWKVMsufZs4g==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ztthFo9C88w4aTJYzR4n/DYbVbtXsRNlpExP2CoIXMOO89FZTWNIsUMheps=,iv:rNcj/Hn2R/4ynIaqTXgQmuwpXFdnB3mJ/AgvTy3At3w=,tag:ZQnJpElMQMOxT4+mdfMWzQ==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:COxAQR2jI9qd94Y=,iv:oXeznhBWJkvG7LOuEoQt4kMnUqWyN4a7EEId4bLnfpU=,tag:IkP3MRICBjvzbeYX4se1qA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTGc3VGI4NEdWMzFCeUgv
        enF1bE45U1VCU2g1REdqcGJhZEE1OU1HL2tnCnZGT0p5YnNnVkI2VGNmaFFJTngr
        RDhrbGdUSjdjZSs2UDdzeXZJMHVXL0UKLS0tIFpGVzdFclJrcCtic1Y5YmVabzVt
        bm5qWGVUMFdCbjR1dUZEMDFDNElvNkEKJL2zoziYCuIZYupoKntAy9XyYsuDuUKh
        p92njQcRyDFwIqAnYwCbL6Hdmt6bzXh84p/gTsoQqnvSEvVVquj6Xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-16T00:25:48Z"
  mac: ENC[AES256_GCM,data:kViXK+d2afBQXHQ3v+eOjLsKVCUx3zhV0pa55vR8nEfmgJp1Lu3g0fmcJZfsglzEu61Q40ZpNBdi1HO3jmnB7GUX8oKadUAfXmU8F95B98QO7l2MGqyID/nW0FoM5zx9G1T1LOhnVpkkc1hzrplyFTicLtUrfILGPMRffGXttHs=,iv:PZnszyEEWtZIaPMm2MjyxNSXiWKbg95r0MvzLmevW1U=,tag:QBsff3TeIgEbOT/sb9RcvQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
