apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: radicale-secret
stringData:
  #ENC[AES256_GCM,data:eni5swPSTRtlwc69IHbyuLWulH1caT9TenE=,iv:qHQbY+HmApjVjDBcnwgAJnWqgMXGGTdQcHlPmHrAy/k=,tag:BiY6fSSJ0hPtvbcbY2/MfA==,type:comment]
  users: ENC[AES256_GCM,data:CB6xMsKCZwbI87Rh5ZbAKSS678VTMeyy5cTxZjvxZHt5OKJtKT8/NuWRsO6qT5olBeRqqJeI+XQCwCfI7Ynyg1aJ466MyzFmaNfnKsNZDtm6Jmsj3gzql6mT3plDCUwRTTq50OlB6oH3MaMuoJd4YaFfWfFx82Mev7cInDGDQDhJXS6uzKXQ,iv:J0xmtyMPmGqTocN0Ik4HHAdydsS3D1X2f7gURHPy6SA=,tag:JUrCZ2rzb3SY7ZHq8EyLlg==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOHJ1a1NoaWU4ZHhpY2xa
        aFdIV0s3MjNrSkljV2dGbUJXU0Z6eXZlNTA4CnQvTlR6a211SkVDakJaZlVHNnd4
        ajNWeXpHdk5qK3hDenBRTytkekQ3dnMKLS0tIDRWK1hxdE9iRHJtT29ESnhrODdq
        eGV2UHBoVlB3OWtKaUJlc0Era1J3aG8KadsuAIBNZjUgK/zCJDW6a6MLlTPdQob6
        w+HfuTprYHeASYNUIAAhRC4+JWdOfSCsFizLN6wpoWRlWDyMZha/3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-14T00:53:21Z"
  mac: ENC[AES256_GCM,data:YS9FGfHCN8zXMU8JyL6Wv4+5vn4p+6fsoqn5mrKJKhg1NInuE2cAVpILY5ExQrqm2/N22ufj+bifbPxfOf77HRguMCQ2EM8g7iidt0D6v9I8O3WHzGVGeN/+LWSntObRfgG9e7NR5Ml+PQ5b4BAREfyIRyqq5P6JLebz1Aiii70=,iv:k0/UG1yxW3MFopfNIBiZPUMq/3KfX0/G4mxhH5gBpzE=,tag:fZxAp18P832ZTgjZOMQDyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
