---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: radicale-secret
stringData:
  #   htpasswd -nB <username>
  users: |
    liana:$2y$05$rsnUUzdkfuC81EKghasNeuJdOj55jO5cca9RxyBOcSgoiaPEGzG02
    maxine:$2y$05$Y0ZB55Y83MJpHWrjNx.J6eXhqqVY3xdogzcS030Kr9sN43laV5F32
