---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudflare-ddns
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/favonia/cloudflare-ddns
              tag: 1.15.1@sha256:a4e2089b3531eec8c9328c7a9a586f80e8d67dcd94856e0b596b7896e1de3f62
            envFrom:
              - configMapRef:
                  identifier: config
              - secretRef:
                  name: cloudflare-ddns-secret
    configMaps:
      config:
        enabled: true
        data:
          DOMAINS: tun.${SECRET_EXTERNAL_DOMAIN}
          PROXIED: "false"
          IP6_PROVIDER: "none"
          DELETE_ON_STOP: "false"
          UPDATE_CRON: "@every 5m"
          QUIET: "false"
