# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cloudflare-ddns-secret
stringData:
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:zhqbufnem4rw7fvkYkT5u6qjvrXnEC5YiOUF9HF/trSgEGKxtM+emw==,iv:Ps/gO1HeI7M8KRQm085MvkDquoaNFIzI/WWB3pjHQNM=,tag:tcUvtVqM5BNX0Wyri6hvCA==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTUFLaFJaWUViMm1QM010
        SElyZWtzVFVXR0E3dVI5SWRSM2RpK0o3cmwwCldwVVFsbkNyMXNzdHBZb3gyRXNS
        c1Y3NGhpRkNEVFFWVC9jZzZIZlQ5WUUKLS0tIGFEZEwwRDNISzVVc0xKK1g5R1ZQ
        d3l5TERGZktnNnh5b0JuS2xtektIMFUKK9rJsR/64Ivn/+QOcv180y00zxUdAqkA
        i/ZzFxgwzIi6NeuXd8X4CZ0FgtEudiLqWa84M0669diEbznxDkeRLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-02T23:52:29Z"
  mac: ENC[AES256_GCM,data:Bf10ZeskgHMTOu33VoxJFXS3/rxMlVc0Lcu9hWE2A6QPbPY11l6HqXQqHiaou3CB5MKSXIFnxNEgfK6c94LrAvh7rP4CoIe0dejLkpRrHCD3lgUxbWIJFtCf5n9kEWXuX+ntxM3RZlCdgbmmFlckUmSVSZYKmFelXwrZg49PIE4=,iv:+DldjI4vrzJ3nl8V4h1tYNk6f14tVc9TzdOpunTczGs=,tag:zX0vbzHjYtSrrAhagBVEKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
