---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app openclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: openclaw-secret
    template:
      engineVersion: v2
      data:
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        OPENCLAW_GATEWAY_PASSWORD: "{{ .OPENCLAW_GATEWAY_PASSWORD }}"
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: "370d94f2-3a15-4fb0-b592-b407000b395b"
    - secretKey: OPENCLAW_GATEWAY_PASSWORD
      remoteRef:
        key: "0c1db09a-f793-4dc2-95fc-b40f015b7ae2"
