---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: perplexica
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      front:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: bfenski/perplexica-frontend
              tag: latest
            env:
              NEXT_PUBLIC_API_URL: http://perplexica-backend.${SECRET_DOMAIN}:3001/api
              NEXT_PUBLIC_WS_URL: ws://perplexica-backend.${SECRET_DOMAIN}:3001
      backend:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: bfenski/perplexica-backend
              tag: latest
            #env:
            #SEARXNG_API_URL: http://searxng.${SECRET_DOMAIN}
            #OPENAI_API_KEY: ${OPENAI_API_KEY}
    service:
      backend:
        controller: backend
        ports:
          http:
            port: 3001
      front:
        controller: front
        ports:
          http:
            port: 3000
    ingress:
      main:
        className: private
        hosts:
          - host: p.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: front
                  port: http
              - path: /api
                pathType: Prefix
                service:
                  identifier: backend
                  port: http
        tls:
          - hosts:
              - p.${SECRET_DOMAIN}
