---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: kopia-secret
    template:
      engineVersion: v2
      data:
        KOPIA_REPOSITORY: "{{ .KOPIA_REPOSITORY }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        KOPIA_B2_BUCKET: "{{ .KOPIA_B2_BUCKET }}"
        B2_ACCOUNT_ID: "{{ .KOPIA_B2_KEY_ID }}"
        B2_APPLICATION_KEY: "{{ .KOPIA_B2_KEY }}"
  data:
    - secretKey: KOPIA_REPOSITORY
      remoteRef:
        key: "9b7b7df3-9670-4209-947d-b44a001d3988"
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: "2eac941c-8ff4-42da-9585-b44a001e6fdf"
    - secretKey: KOPIA_B2_BUCKET
      remoteRef:
        key: "631f7630-8197-4c12-8bb9-b44a001d18a2"
    - secretKey: KOPIA_B2_KEY_ID
      remoteRef:
        key: "46f494a8-b5e2-4e9f-b386-b44a001daa52"
    - secretKey: KOPIA_B2_KEY
      remoteRef:
        key: "2cb2908b-f2e6-4d31-ac6c-b44a001ddb39"
