# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: miniflux-secret
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:90Um7W4=,iv:GhBR9iXU+kfYRBgVHx847ml9M9i3bwLWMBxJQU7oxc4=,tag:UJayN/ZcJMr2g7ivDBKmMQ==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:otDLrzohdasc5SmZx9MrHmtCZ1XueKIkuXjo/w==,iv:6YSFP/BcruDuFtwUhA9z7XuB57bV1y0dY9QXIgoi3eo=,tag:eCT9DMJNB5VsEGR6h3MX4g==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:YztIPpHej2A=,iv:G6bJ5Q1xm4wYbts0S3OIUmp9uOv2YF8PV2NSsMoOlag=,tag:1OmN01q1ebbOLMqPf48HZw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:V10LzJZebIygxyNrKPnYJdMkWE64N9J3/mrnSA==,iv:5F4F+HsHFxb0lI1WTP4DLYszhTrlTHZiyT6ElCbeuRs=,tag:H+bnZ4fFb23qh7u8SG0rCw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:PSQDrkW0LTRzcZ9nffpmc6P0GmYrQeLY9P2vhO37nRHjBVWVB99C4z2i3AUokgTNDKqn/EuVahrzdpVOiZZ/9Mdoi9A66sfy/nzqFbUZ+1YDYDwBh3kFQ5AqCA==,iv:71xFJtZxPaoWzZ8yOJFT4ajpCU4DSxceF2y6G+NoZ10=,tag:AAGbmUQwZk+EOMa7Jo5K8w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Vk56L3ovRXNSQ3g2UEdC
        WUtLTUp2MDZjUUVmRVd0ajdIcDhnbzcycjFRClhXVzNUeFlnMVdlZE5oa0RWbmpj
        NHFhRTlpWWpFbkh3ZW1SOXl4ZWtYcmcKLS0tIDdGSzRXN0cwRDNrQjIzNFFEOUdx
        WmtRRWRLc0dzc3owT0lUa1l4SktjQ0EKBNgvIkVEuiWP/plFW1uZyyAxZciWMbUT
        tW2B+PmdrW5p+vMxpBZEmoisKk4arSMFdZBvq5nrtFEX3N/yPtydaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-11T16:22:46Z"
  mac: ENC[AES256_GCM,data:Npi3OhqAM6qB0otA8dQOXV17A5d+DYA58IdUwxU8WQDBIeJzkfJY8MGHyV9dCBfIQI3ktmgzYGOMteOgaWOpEIOqPk+nSZ4u9/7VN5ozKv0FbVNgaRoOhbGwsMivxtHjptJll8tLLOiDtZZtQAtX2nCy5G/l4RaACepM0JMq0r0=,iv:sOpmA9wMhzGuJa2U4UYPPvMG0p7JYsoSYqpl4dONzjE=,tag:oAcl9Gcf02j8SU2WEFPZ+A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
