# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: miniflux-secret
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:M5+WT1U=,iv:9hkHWhhE1WNLuzcriIUM5M1/TDe89+PVhY9ljEamw88=,tag:7S/SC1V10QCiKsCoPg8Qdw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:z44qKP3m679RBd8VSbogTEYTW0H+Pwc5IFkx+g==,iv:PQ4pL655B0nRgamo2luQn+IRha2NfHJ4FlGHAROb25w=,tag:qJUMjW0tMJtLxW3L+znX2Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:useee4LP6zg=,iv:lQBf7NgPL/xryo29wP0pQQdDXIlqQKnlUr+iKNzfuWs=,tag:AtGVqiCDqXoZN/ehIZnp3w==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ylDJD13yLGl7+wNG/Q2qA9onsA5a0MVLObtPKA==,iv:7nUFm0krFOUked0w4vUUwOeWMZNbsfFY+NqMMIL5mtA=,tag:7TPMzUQIaRnYvggLQPtPiQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:hZFsJdsrljVUR1MwOsSaYYLJ6k6SkNAn+N/8g08zKr6eskywIZ5W19VStuvIrQtTl9L2aizaXgT9KWq8/G+7f+l1twzqT4Mf4KxAZQHQG7jsEZalbYMlZutS/w==,iv:EzgdIWNpFcsd1Qm2VHpWhHt2j4Yhq68XwptgTZVKMIs=,tag:6zGt0uiDQq6QTNH2HwLInA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbStjVFJYMTg4ZHRDM0hI
        RXZURVRPQzNsSWNSejRKa3M2OStQZW5HR2xVCngyOFNORktZSU0xRmlLdlVQMU1E
        bVgrTk95VHFhMEpxUzlYQjFMMGtHMzAKLS0tIFo1eXd3WWVGemVMQStJSUVneW0v
        cmQxSk9uVVZybmg5QXdySWFCYW1zMmcKyVu8xUzKBcdbrucyntCRy8iQQYMxQL6t
        WfimUb85/GWGHwWKQanjfW3wlXNQ1XWc4iMmgXyLwNVr3YXcZbGLmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-11T02:58:15Z"
  mac: ENC[AES256_GCM,data:THAGMOzECApu69x+O60ggtfofh6PMkXn/bM4DvmytPzgm3sg8djLFQevvznBJL+yRpWwLa4a1DFYOqEV1iGBBCI4x5rQj7dYRTJEG/QS2gZa9iSETb/cRJVe/NiLgynxaq9n/Z2/MI2xJaCzu/xTAhA6ifIoQpH1K/Cm0ioSIM0=,iv:gtT2BftRpyHdSlKVVkCO1dVpyS9fa51CFFTLtfZirxY=,tag:5VMfJixyMo1qggF8P2NNVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
