# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: miniflux-secret
stringData:
  ADMIN_USERNAME: ENC[AES256_GCM,data:HLyNA/Y=,iv:xrtw5pG8oEXqRKu9Ysx9BWaWW+OJmjKBhCaq+ymaBIw=,tag:GACvUVs6P3zktc/J3hslhQ==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:JVsoZDlU8vKoMGXYUIjKNchNYbK7snFobJ2TDg==,iv:5kbVh0eyvfCE1iifshVlV9LITTTegs42RtipG5pWPoI=,tag:2na2E3Uu9aVNZcOYWxOM5w==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:CaTtCKNDCD4=,iv:P06ii5T8+ufuMrP1s93siU0uvn7XPB+PRq1j7cneP1k=,tag:7XXpmlEZyQpMQ9P5K1t2BQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:nk7ZMEll3/d3WS+fKZyyPGQs3aTbxm0sad6U3A==,iv:4HxUOEKJWDZOPCJDA7iOl3uwvk7MkebOBM+qCEHXNb0=,tag:dN4rlgkors0zGUquGFxHwg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:YlKLFDR6Xju3Aily73t5pVEBa0RkA0RVgk1YnXaDqmNW4fi+nJp1F4+6BDWeVQzVbE97gDG4c+SW6yTGuh40L4fWTnM3KUYrCZwVS3kz2gHMew==,iv:ht4uyAC02hZ4x/wfpbJlaEg53VLqKeAeX8TtObWujfE=,tag:73DvuHOTYik4hwB+B673vQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NnRFMFBDK0t2aVVKZWtS
        anJmU2w0b0ppcGZCYWU3WmJwd1FtQS9wTkRJClFxZFNYbmFpVUEzYzRkb29sVExT
        ejZFcStZdytLT1JQMHZlcDNoNGpXRjQKLS0tIDI5SDdmNDNia1crNmRIaWx0RDI3
        cElWVkp0M1ZWdnhHS2NFbFpFM2ZyUFEKx7sJeUfpdOPOloZY/CidI08WViA1S3ci
        2OstV6trF5DK7pVYP63ggPdj0U9fQ99Z4IWsR69N4KS/eUaPrwO2cA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-11T02:57:11Z"
  mac: ENC[AES256_GCM,data:4j9NZrPBsHP7U5yppfBxPQyx0wsZ3Ioin/cvPU/yCektVBdFAdN58W++jvhyVN6RDY8fTA2/CZqnTBUbtzsVHKKJqbA0/1yA3YiYB4f3Z++Gg22rFR6wuuI/EOtE0e4cRI7EvyTXpkcHZMG7eiHsc3nkQJQ+j4a2VZD/djofQRY=,iv:1R5DLzTWmSXSzoXtGW3o5MzH5XC9o9Hc3IR18kWDCq8=,tag:tWvf2xvv74c1AfRJcYk1Kg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
