---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-1-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: postgres-1-backup-secret
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .CNPG_B2_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .CNPG_B2_KEY }}"
  data:
    - secretKey: CNPG_B2_KEY_ID
      remoteRef:
        key: "3d7df7dc-11f8-43f6-ba40-b44a0021cf6f"
    - secretKey: CNPG_B2_KEY
      remoteRef:
        key: "34b9e5f4-0d2a-4f71-b07b-b44a0021eb3e"
