---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-1-backup
spec:
  configuration:
    destinationPath: "s3://${CNPG_BUCKET}/postgres-1"
    endpointURL: "https://s3.${CNPG_B2_REGION:=us-east-005}.backblazeb2.com"
    s3Credentials:
      accessKeyId:
        name: postgres-1-backup-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: postgres-1-backup-secret
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
      jobs: 2
  retentionPolicy: "30d"
