# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:pvyPbML/Zy6kNojkUUu47KpvnKlphwiDZutvcQ==,iv:TgAD23Ecs4Zx/7GlzfPYmOvsGnmv0Co/BQVkKHAZw0M=,tag:UnRU+oeQbEYoSGx31KvTHw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbUxGN0o2TzhrVEFBSDRO
        Z1RZZXg2YVA0YzMwa2lCSlpEQWtYRnMyblV3ClcwT2Rscm5sUFRkSUVaL2VUWGZ1
        Mk0rY3Z5QnBWOFpxc2FXVjlPQkI0ZzgKLS0tIHhEWXoxMjB2c2hjU0NKR1Nha1Zo
        clBpdXdZTSszQ0J4QWp3bkxEVWNFTFUKFUnCafT0bYkozGiNSeJ3oDDrcgkK2VhP
        Lc9sKPYSbRRhNweR/8k2ks4a+ukJrlCxlIjYfX9QgE+84qplujDOpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-11T18:41:20Z"
  mac: ENC[AES256_GCM,data:uqEV/3FgL9fSlRGyYwZN6OlWe829NEAmTXAsjhb7EUCoi7D+raPrpaRfEESEBRJ3bejfssmFj6U2xTaQhGboE0jeoJKdkLLR2c/Wnuxfmfw4rC53oAkc8klpoCneL5Vp/jNlSijKzZgXHCpg+g69CuJC2N4fZtmJkzlZCqhA1dM=,iv:4IUcANqUcDdAhcezbUUhdGgjfXIL8jbjRGRjxEDND0E=,tag:N675xUG51Vwch87RDebNSQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
