---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app superset
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 0.12.6
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
  values:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Apache Superset
        gethomepage.dev/group: Services
        gethomepage.dev/icon: superset
      hosts:
        - &host "superset.${SECRET_INTERNAL_DOMAIN}"
      tls:
        - secretName: superset-tls
          hosts:
            - *host

    postgresql:
      enabled: false

    redis:
      enabled: false

    envFromSecret: superset-secret
    supersetNode:
      connections:
        redis_host: dragonfly.database.svc.cluster.local
        redis_port: "6379"
        db_host: postgres-1-rw.database.svc.cluster.local
        db_port: "5432"
        db_user: superset
        db_pass: "${SECRET_POSTGRES_PASSWORD}"
        db_name: superset
