# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: superset-secret
stringData:
  SUPERSET_SECRET: ENC[AES256_GCM,data:8axejEwSNutDAzYKqtd9UCsTQr5LTSJLQXp9CcUJFqZX3gyoUijgnxANBc1Nn4YhSA==,iv:88TZthTQKmA3tuvO7YUtYhFQhleGRpDzkUjXnDsbpl4=,tag:eLoU7Hs9pbpqPTg4u4nbLg==,type:str]
  SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:3xpCaXrdZTUs0Wua2m1YlLdwjSVE2A37kQ0+F5PfQlY=,iv:omYdjQDE0GwoDT/KHkw/1bCe1D4JKNtVEiFlUVePrgI=,tag:02wodg1BfUCMk2SR9png0g==,type:str]
  DB_HOST: ENC[AES256_GCM,data:6qB9lsUcbOPlGyTZODEGb2CSUjxdZFIvtn/uAGtkSgR9BWUkpZz1ig==,iv:yFK6z6WayTc/MFEyM+us/eWoLokyQy99gEDlUZWq1NA=,tag:w4x60YQ5yvbPreIqYXMfZg==,type:str]
  DB_PORT: ENC[AES256_GCM,data:1z95Zg==,iv:wIh0MLtojnya25D4EdMp2NBF8pPRVgKA1E2pCwMTJM0=,tag:kxqx1nYyBbNiveGtg4jaLw==,type:int]
  REDIS_HOST: ENC[AES256_GCM,data:/LdjkUT4C/TzJV9nTzga5QfnNDqcJAME5tTSD7BO4sn56fe9,iv:6l2vJAuv99uwmm6R90phIZbWY+nXRfCPAwrx1XFesjE=,tag:+K4rMoLgfcsRlfuF761Brg==,type:str]
  REDIS_PORT: ENC[AES256_GCM,data:zR7Nig==,iv:B3GyoJZqRAGYZ99RPTXC4LJzwwRlLdNlbXJoOMz6G/8=,tag:uiWlBN1kK+RDZueAaVK9tg==,type:int]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNDJROVpsQmlTaktvbjJY
        bzZYZXowMzJqdmZZbzRHR2VTSXJtZG1MTlZnCjQ0MVdnSXgzZEVPUm1TNEdsb1RV
        NTBhWjlYK0dDQVExRHBPcmw5OEdKK2cKLS0tIGR4Q3RhZ1M5SU9kODZydHpUL0Ri
        akU2b2tOZjFHQjA3SFJweHU4eU9iNjAKUZ1x/7GNPNqk3Fp6dOReQ9E/Wnq0R6Pw
        oxekWYUJNTtW/i9DWkURx0t/OJLi5gjJtU/f12Uil+NtigNlrFuWJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-13T19:37:03Z"
  mac: ENC[AES256_GCM,data:imOAqIagwTagQnH6+WJQNrpupP7bGlFjW7/EOwD3YLE3J3V3PvagsiI3S2LPskteeXNtmWUVrEZO9nG642DeAUR25hPuPQmp6Abs1a7IvQSM5zWOoVleZz2jQfRH2MRfx/9949Qt70L1QtCJ+DvQsILKJYhmhCIczxuS7PTh8qg=,iv:jFWyFNe51guwtP6PAIyckwSrTG5j8VP16e0yiwAjdm4=,tag:VC64CcbqQn4/QY+wuVIb3g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
