---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app netbox
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      netbox:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            env:
              INIT_POSTGRES_HOST: postgres-1-rw.database.svc.cluster.local
              INIT_POSTGRES_DBNAME: netbox
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: cloudnative-pg-secret
                    key: password
            envFrom: &envFrom
              - secretRef:
                  name: netbox-secret
        containers:
          app:
            image:
              repository: ghcr.io/netbox-community/netbox
              tag: v4.1.7-3.0.2@sha256:e88d5e58dd32d643d8d9851f6c9edde20a69a87fd4a72a14259d045f6d3e19d3
            env:
              #DEBUG: 1
              TZ: ${TIMEZONE}
              DB_HOST: postgres-1-rw.database.svc.cluster.local
              METRICS_ENABLED: true
              EMAIL_USE_TLS: true
              EMAIL_PORT: 587
              GRAPHQL_ENABLED: false
              HOUSEKEEPING_INTERVAL: 86400 # Every 24 hours
              MEDIA_ROOT: /media
              REDIS_SSL: false
              REDIS_DATABASE: 3
              REDIS_HOST: dragonfly.database.svc.cluster.local
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: dragonfly-secret
                    key: password
              REDIS_INSECURE_SKIP_TLS_VERIFY: false
              REDIS_CACHE_SSL: false
              REDIS_CACHE_DATABASE: 2
              REDIS_CACHE_HOST: dragonfly.database.svc.cluster.local
              REDIS_CACHE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: dragonfly-secret
                    key: password
              REDIS_CACHE_INSECURE_SKIP_TLS_VERIFY: false
              SKIP_SUPERUSER: false
            envFrom: *envFrom
            #            probes:
            #              liveness: &probes
            #                enabled: true
            #                custom: true
            #                spec:
            #                  httpGet:
            #                    path: /healthcheck
            #                    port: &port 8000
            #                  initialDelaySeconds: 0
            #                  periodSeconds: 10
            #                  timeoutSeconds: 1
            #                  failureThreshold: 3
            #              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Observability
          gethomepage.dev/name: NetBox
          gethomepage.dev/description: Network documentation
          gethomepage.dev/icon: netbox
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: netbox-tls
            hosts: [*host]
