---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: open-webui-secret
    template:
      engineVersion: v2
      data:
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
  data:
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: "aca5237a-f38e-48da-97a7-b43e0173523c"
