# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: recyclarr-secret
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:sncMBGw63qFEoHuvIL9CxgAi6d1fNxYEDXRGUoz1mI4=,iv:aiGxYQTHkwJc5bm5F4+Vz7M4wsb4JXOftF2vAdcI5sc=,tag:euBfPJd/o2AcP4t4LZhzsg==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:rXUMWS03sdY4h+QwTm1RWWcL1rrojKJ4xGSTrFhI4b0A2c8I/qxa3f1JB08=,iv:BU88e4353E/lyQ2JX4lSHA9QQyK3Scym9pAvI0GNDLQ=,tag:ujnLg40wa5dEFwAJ9brfKA==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUTRuN3FLdmNLK2RyTFNN
        eSs2YUJHL3ZUbmwvZHhnWTVPaHQ0QVpMTUg4CkNlOWY3MU1pYkwycEZ5U2NBeENB
        ZlNzL1dUQktFbDg1RDZKWUhZenZrKzAKLS0tIGVSaXk1ZTErN0FrZlhPekNKK3g0
        Tm5tZnRudFNYa3JQMzU0NkQyeDI5L2sK1ssXUDQEilWvum1JbHSpFaBJe8dy6uVA
        fzsS9BOZoNY2AfCYNmEuO7f7v3aDfyWb/yfj1OKEMg7LjJLbveu9Sw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T00:40:36Z"
  mac: ENC[AES256_GCM,data:uNAXpPMgSQbDF5kYeuEtWEh1+mM/TvaYNxBY1EIjEkEL+X3Hf8TK/C0+fpfNZ49dQjTwb7AG3oHOwuqH/yM2TZ7QdX8SMqIYp6e10peYbAT5/kJ1AodkAoWxrM4f//pkYCBPeGpG657PWanMzH7tvzFKmve68BwAReuqpmaolvs=,iv:h+M0rtcJUb7CwieuXIuj1mr3I1I0KZjAuJHzRfyW8bg=,tag:VpwvhHpkeIgVwEv16Ny/5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
