---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app owncast
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      owncast:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/owncast/owncast
              tag: 0.2.3@sha256:823b6c1346639d93993a810748e906ff73291c0445bcb8ca8cec4b3ed28238eb
            resources:
              requests:
                cpu: 128m
                memory: 256Mi
              limits:
                memory: 2Gi
    service:
      app:
        primary: true
        ports:
          http:
            port: 8080
      stream:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${LB_OWNCAST}"
        ports:
          rtmp:
            port: 1935
            protocol: TCP
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Owncast
          gethomepage.dev/description: Livestream
          gethomepage.dev/icon: owncast
        hosts:
          - host: &host "stream.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: owncast-tls
            hosts: [*host]
    persistence:
      data:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 4Gi
        retain: true
        globalMounts:
          - path: /app/data
