# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: sonarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:nzWAa3JlLK+sUytKIohzb0A/RU+oA4eykE+J0DUPgF/Sg+hoc9Rhx1oYZ38=,iv:bHKEDEm+jeoJqTrVg7up+ULWAcg1TNu6X5vo4uL8N2o=,tag:ZC6b+oglJQEyKeXoN18feA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYM3B4S1NNREpiTmVKeU1H
        LzJtZkYxODRxWkxrVFRYc0VkR0haMy9ZK0JnCnlzNEE2Q2VUSWZRWTFWYW1JS3pi
        TS8xZXY4cXFiREduaGFYYVV0OGtQM28KLS0tIENnbDRTTy9sUzlUcS9UeUczMjk1
        NFg4eWk2bUhVclVpdXBjMVVSWVhtb2sKgQdaNskSYXdMxbA78HMlRsaS1xauT2ep
        n7GV1tlIcQWYlPrj9KM2hTVeOGtmWp+uZSF2D/cuZ0xA4/EqyX0z1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T02:17:54Z"
  mac: ENC[AES256_GCM,data:wmy1wYPD6Yr4ilHGuTHoyWd/TpJttI0nL9LGYHCVZ5isO+sYha3r1ofBv0LbJERbfRMhfjHJKTmu8zd3KTAGMRvHr1GQOpL0G3N5MeyfWBs9t+Vgh1hr/i755g00+yxs5Bio/6hbIChXoHKogNY5iaMqt2u91XumKDmGYEU9CcE=,iv:C/bbtc7PPGPjhNdkk3laUz1dD077nnpmOw5UQ7L5kqc=,tag:ViCr7BpXMfXScesPeSj8zw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
