---
# Note: Gatus vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
web:
  port: $${CUSTOM_WEB_PORT}
storage:
  type: postgres
  path: postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@$${POSTGRES_HOST}:5432/$${POSTGRES_DB}?sslmode=disable
metrics: true
debug: false
ui:
  title: Status
  header: Status
alerting:
  discord:
    webhook-url: $${DISCORD_WEBHOOK_URL}
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    url: https://status.$${SECRET_EXTERNAL_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
  #  - name: flux-webhook
  #    group: external
  #    url: https://flux-webhook.$${SECRET_EXTERNAL_DOMAIN}
  #    interval: 1m
  #    client:
  #      dns-resolver: tcp://1.1.1.1:53
  #    conditions:
  #      - "[STATUS] == 404"
  #    alerts:
  #      - type: discord
