# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: gatus-secret
stringData:
  SECRET_DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:so3BhTnLo59gvVKW/+RMCCLjuFvF57zVsSVFNrB8yAgxmpOEl4gj/gGvoxQT5LM8wNFQ5aXoyfW81R826d1c8SrcWHEUvdmPRsOvzrjiwjUhygAXUO/B3v5hlCbSMvK54erlcbUWZsUukc1Idt3DWConBLkDxa4H1g==,iv:41vIrSsS8J6Dr+egmSEeS+Wt9/wJZBZ7JMvDp2QEq9k=,tag:6wzRr6Kc0OPfSHHZJumVpg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:fhDqwVY=,iv:4a/KmX8JGQ/BxpNSsFEVVpEcW8hHSuWf3pCsUo/6NTo=,tag:xfnxxUWp5TP5atKTUZwLFQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:izRoCbICYy5811nZgNaYiNKZhqsdNpxJ9Ne7FevqNMq2ccerv4sF,iv:dWQiE8xM8tyQPfgoTWNwXIqynev2mVBTLpPYLdAeBWg=,tag:VcEuRNYNVFvR0KVv7qiUrw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMTlmY3hUaS8vMUpuRXVv
        bDVNa05HMVBoMm5yWStOY3N3VFVGZWhOZ3hBClZPam40ODQ4ZCtOdjV3MHJ0Z0Yx
        N3huQ0JLcUpDdTJnQ1RBbU9YdVdqVkUKLS0tIDhzMjJ3TTVsRjZ3aFJib1ZHQWpt
        QlBmVFJIejJhUk9oVjZHOWZNUWpHcGsK3NmDs6wUnhEzLwG3BKbnX72abJcGFSLe
        /ucD0QFzwVurpUZs1Y0TeSBokU10tkb72mhB0lbPzZAIvD96PQ0bsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-19T00:27:03Z"
  mac: ENC[AES256_GCM,data:R3KJjBu6uUrpL+a0TCa0ssqkTemlCj5CHIEFdc05sQ/zrOeVNHjsFwmBW+HWVOiSL5Depzjv34/yQiywp9tXp/3KPJFHzF5sTt363o108KtLHO7/Gj6ZSQ5pS+gp4Ubc9kgLKcMmdr+KX4yUs/Wz5Diz2DdvkuTmUrmTBm80g3I=,iv:5uduJOYoAObCcDfVoQaerssUN3OPkWX8MoAXgTQaFm4=,tag:H9NCduoOCjPVMJDCwKgqAA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
