---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apprise
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      apprise:
        containers:
          app:
            image:
              # https://hub.docker.com/r/caronc/apprise
              repository: docker.io/caronc/apprise
              tag: 1.1.6@sha256:7b4cbe23581912a51f13648da746c2e38982d4faf1c20d0f54f961a3381a9b4c
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      app:
        controller: apprise
        ports:
          http:
            port: 8000
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Observability
          gethomepage.dev/name: Apprise
          gethomepage.dev/description: Push notifications
          gethomepage.dev/icon: apprise
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: apprise-tls
            hosts: [*host]
    persistence:
      config:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 64Mi
        retain: true
        globalMounts:
          - path: /apprise
