---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport
  namespace: security
spec:
  storageClassName: cluster-nvme
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
