---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app traefik
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/networking/traefik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app traefik-external
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/networking/traefik/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
