---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# NOTE: skip sudo and NET_RAW capability are required for rootless autopause
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: 2024.10.2@sha256:8bd119f65ef6e65bdb12f756bfb44a305b36b1adf868ade8027014fabc29c755
            env:
              TZ: ${TIMEZONE}
              EULA: true
              SERVER_NAME: Shoujo Magical Gamers
              MOTD: "Medieval Edition (1.21.3)"
              MAX_PLAYERS: 16
              MODE: survival
              VERSION: "1.21.3"
              DIFFICULTY: normal
              LEVEL: world
              MEMORY: 8192M
              JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
              ENABLE_WHITELIST: true
              MAX_TICK_TIME: -1
              MAX_WORLD_SIZE: 29999984
              VIEW_DISTANCE: 12
              MAX_BUILD_HEIGHT: 320
              SPAWN_PROTECTION: 0
              SKIP_SUDO: true
              ENABLE_AUTOPAUSE: true
              AUTOPAUSE_TIMEOUT_EST: 600
              AUTOPAUSE_TIMEOUT_INIT: 300
              FORCE_GAMEMODE: true
              OVERRIDE_ICON: true
              ICON: https://i.ibb.co/q7PkGt4/shoujomagical.png
              TYPE: FABRIC
              FABRIC_LAUNCHER_VERSION: 1.0.1
              FABRIC_LOADER_VERSION: 0.16.9
              CURSEFORGE_FILES: |
                balm-fabric:5848095
                collective:5847007
                glitchcore:5884524
                fabric-api:5937030
                cristel-lib:5871655
                advanced-shulkerboxes:5850153
                waystones:5841762
                serene-seasons:5861336
                mouse-tweaks:5856191
                towns-and-towers:5871683
                gui-clock:5847307
                gui-compass:5847304
                hand-over-your-items:5847302
                husk-spawn:5847275
                pet-names:5847197
                stray-spawn:5847085
                villager-names:5847043
                dismount-entity:5847382
                stack-refill:5847097
                bottled-air:5847458
                cave-spider-spawn:5847436
                areas:5847486
                spark:5924846
                chat-heads:5902516
                first-join-message:5847342
                bogged-spawn:5847461
                animal-feeding-trough:5877750
                crate-delight-fabric:5928450
                dungeon-and-taverns:5835774
                idwtialsimmoedm:5886289
                basic-weapons:5905709
                weaker-spiderwebs:5838129
                spiders-produce-webs:5838662
                random-village-names:5841918
                double-doors:5839965
                grindstone-sharper-tools:5839909
                architectury-api:5850077
                journeymap:5947314
                xaeros-world-map:5890989
                natures-compass:5914932
                trashslot:5856665
            envFrom:
              - secretRef:
                  name: minecraft-secret
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 8192Mi
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: true
              capabilities:
                add: ["NET_RAW"]
                drop: ["ALL"]
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  periodSeconds: 60
                  exec: &probeexec { command: ["mc-health"] }
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 1
                  failureThreshold: 300
                  exec: *probeexec
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: Always
    service:
      app:
        controller: minecraft
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "shoujo.${SECRET_EXTERNAL_DOMAIN}"
          external-dns.alpha.kubernetes.io/target: "mc-router.${SECRET_EXTERNAL_DOMAIN}"
          mc-router.itzg.me/externalServerName: shoujo.${SECRET_EXTERNAL_DOMAIN}
        ports:
          minecraft:
            port: 25565
    persistence:
      data:
        storageClass: local-nvme
        accessMode: ReadWriteOnce
        size: 48Gi
        retain: true
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
