---
proxmox_base_packages:
  - sudo
  - vim

proxmox_users:
  - name: ansible
    nopasswd: true
  - name: liana
    nopasswd: false

proxmox_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCr5g6rtghAGWkO/fDfFDOS0QszZCkPrCoFo6hynf4n26sqdMyb14leWuRnYbro/HinDBUvv6AlsESc6NCfJmWuYP2fge3lhj+figX85uZX0ladFErHWKvR+M0ROUtBAXpcafDh2NYzoFYJyb6gwoCRRepduS6HGZN+XTbcMOSsqZXEdmHwArSkyJpRv1pN0YSKULkcOFjqneQ5+seVu0Xch6xAC9EPx33XcWcM2A7lyRVDd1cuahjEnW3YDY0MNgjxfqMcvV43C2k3MWIpmoQYx0Q1OlGo37iPtS+236qKjUN8+DgQSK54K4KTGULJyu9RyWzwDwHg5V7pUNjV8Yxoq/H3nA7C2aZyeJzEHz6SnrtDWdeeKYOYtD/c0v5vnSqwV87WjBCUJ7Q6Bz6MP6pjuYdrKKkKv9IVnG1kOkEaMDMJlIsTkFlAZKkMjn/TTd7NhuAHZhfc/pwMxiEcBOkuXxr4I1ENkZKRLcySq0LzB5MnzLlIoqP27tcYV7Hczbp3PDCpIshukf54QWK18tNiQRzKMnzy8daq0tE45wYZcOSSsceTbAdLceE8xhDBHkXymqHHFq2nDrVuOyIQLr6N2Qafwad7OHd2iF0PIsGXezZotORkQBZqY2XEp4CFueMH+4Fc9K4zot8CoHTaJux14AtBCmqMXUaO2poziAtXhw== liana@2024"

ansible_user: ansible
