---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      bazarr:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            #fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            #supplementalGroups:
            #  - 3005

        containers:
          app:
            image:
              repository: ghcr.io/liana64/bazarr
              tag: 1.5.2@sha256:266508f6fb7fb26c9c208cd32c3295a7fafd7fbd5d0eb41727fdf366e81d9f33
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 6767
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 15m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: bazarr
        ports:
          http:
            port: *port
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_EXTERNAL_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: Bazarr
          gethomepage.dev/description: Subtitles
          gethomepage.dev/icon: bazarr
        hosts:
          - host: &host "bazarr.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: bazarr-tls
            hosts: [*host]

    persistence:
      config:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
          - path: /config
      media:
        enabled: true
        existingClaim: qbittorrent-media
        advancedMounts:
          bazarr:
            app:
              - path: /media
      #      nfs-media:
      #        type: nfs
      #        server: ${NFS_HOST}
      #        path: ${NFS_MEDIA}
      #        advancedMounts:
      #          bazarr:
      #            app:
      #              - path: /data/r720xd-media
      #                readOnly: false
