apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:liQdXMQCxLuYUsoEfcEzQmkyc8q0Yrt7svOkn2A+KCe/GrxrLTUf6Q==,iv:JkW7qLGJjJgNXZx+2oZtgvCFn3ATiFo/Bb6xdV29spo=,tag:+W47LDpQFkKMROfyKRUmYQ==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByR2pndTNzL0FJR1lTTFVF
        SlNZL1ZoRWFDSTRFYkZaTzlCUmowZzNIeTFFCkw3alJUcmloQXllL3RxTFYyWmFY
        Tm0zVDJTZklnQUR5aDQ2MURPb3VCeFkKLS0tIGkybS9TMlIyeUEra2MzLzZIVFA5
        QTNGcXF1UVdUOGwvRFJqaXkxa2ZIdGsKOfDDUYPkoq/JxGjPCI6hRl/4HKZ4udNl
        pAKOW6RcM7wk6mI6JzeuulOsiGjcmtN7mEYHzB8pyjEh78TckMCKaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T02:45:22Z"
  mac: ENC[AES256_GCM,data:BR7EjvgnhGpTiMYLT9HvuB5w4IJTP0zDtUCWGSMJWk/AV5CtTXa502yV4XujIvxafcjznp6iQ1qq5VpZXXMhL52Nyl7C2BAuPKtxMA9pkK4oL/2/Kb2NsqGDmurs+xLheqE0QAXjmdOJMQev21kk8OoGF+4kTz6UEdgpUS/kz+U=,iv:DpQdfBJ27uMQ5ajXbGuaFwHZc+G4pt5Yg1JznVpkCFg=,tag:pErXLk5p2mUWIYJym1jLvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
