apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cOW2K8EiI38oxb2I4pur2fjxxmhcmKviS4DPZxRUf9CUvsbq0wy2vQ==,iv:CefmlNdBZIQ1TNywZB4BMVdL77uofr09H4GWnf7Rgdk=,tag:1VqddHXdIq3eO413QdUCmw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVGlDSlVFcmhBblFMU3Nk
        MTQ5SmZVYlpKV0xZeXczbjRoeW1UVmlWckQ4CkhlbE5GWS9xb0xIZkJyeGRKVXBP
        MnJQYk9ZbXBST0tIMHhTVklrUVBCeFUKLS0tIDhoK1NHd25mWUZlTEhyMTZNU3VC
        blppVW9vc0QwRkU3QWszVWVEOGl2THcKaPQ3dxSzkfdRPtpOOpoNW1lOiUCgBhHX
        8ldxgNStgkfdyLvE7BrSwWdcXm8Q8uy3M+RlaAYP6uAmAy/BnAqmiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-10T15:05:01Z"
  mac: ENC[AES256_GCM,data:0goOAO6zLeEK1f5F4r9tzCPXJYOt0mEJWN9R/hR9k58b3cAwBt+9lRlFvb1rUZyb1dgBGix+pHASZG4idVEqTdpI5ZfgpeeLpqTpjLMI18vTz36eZ8rVzwVDjDLZhVeqBBxD6H7IAU/ecPVowvkxwosQuuM2yE0jjAg38EGA2uc=,iv:ebq5xrTmSaRMSJ9E1q+T+HX5X0/D+bLnZcpSSnxw9no=,tag:s6UzCqRSyJDCSNchetnHKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
