apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:yDoGOqWzyYN1q5VEUzhEzsAGGgUYjR4tOg9J98W8EgKNLlkcuiGJaA==,iv:oBYMT7HXgxzVWF8hL+PeaJazxQHf/jk0DQme9c6EGDM=,tag:cRfdRyAH0beSlNIUMsJW2A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSUwwNm0ycXJ0aWNUZjR0
        dHFib3FleXNsZlFNU1AyRllPeWlIZ0swcFdjCkM1dVNnNWhTYVRvb25CSU1jOVZh
        NFNkbXlOTlpkc0lLdXF3cmpsUVp3MWMKLS0tIExoOHhnNVpkU0NIbGVNQkxRWGJs
        U0NvZjFsR0Y0dUFCTFZxNjFsUjdwTkEKd0azTAjpwoDGbOoHbSH0eTyXxczRyTzj
        HVhuLj/+LEH3k2/G8IKNNwIf4oF7hV+f6YAkhATYxmbR8Ft8+CtamA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T02:17:53Z"
  mac: ENC[AES256_GCM,data:EBsi22NIYWNz0/Sh6/6zpky3TZko3j9PEvC+X+n8d7f2juiRnUkAykPWfwrko64KltbzY9Ccn8gwHAM5zVSEKaYWPB6qqJ5LmpGtcbqEmrUEVPnOoDk9FMx9ZzDUabyRoyQrHFmM5zgZxMMsqQzxG0QfWlnYFrvkVnAICv2voMY=,iv:j/9nfAp6Lq1xS810l5DurQaG/Gc9d7Fp+BA1aOD2qdc=,tag:0BOJqz4jS1oZz6De9sinXg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
