---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plugin-barman-cloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
    namespace: flux-system
