# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: plane-secret
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:pyE8ZRQex5957x5VDzpeSReEjyHVd/rk94VHGc7HG4c/adp7lxQHkPccnANEmykqwtqJg6KtqIIsS/YpryHGYw==,iv:30hN0ptSC1JYSMKAHLF7IAReblrMfwBhzMlaTP79jCw=,tag:BBFQyHFmkLyr8Nyhbn6xyg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:ZZTLn2U=,iv:qm5YKuCIkpnz3uJQoVTs3B8Vxsc69YnAMCzCoRUiqgY=,tag:0NEF0vkUJ0dJQwzk+qJqRQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:KwXEG2Y=,iv:64EbD5HwoXTWbxx873BuYOA5fIOhNiS+aOaLP58sMwU=,tag:+zNWs1POt6AY6xhcIylbQg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:1tkv0m6ydV6RlYrIFxceroBQTqr+Xjfdmadm7riFPB4=,iv:SgVnc1RIjCHDx4GKA9jQgx3YCvIg4QWIiZUqr7UZRLY=,tag:9ejNoI5L3Jbo4xkbTC3Z+Q==,type:str]
  POSTGRES_URL: ENC[AES256_GCM,data:jdFVXgLI2Qv5jJmGQAhHTu0XpxGu6JPuFG3PTBW4baAP4QcbZ+KPs+613s1wTrvkBWJojozmIyromW10s9g7Bw84EuUMKGfHlaEEI8m67e0vd34S1IMdzLqpP/lpmurpubCJLpjfoQ==,iv:+jzI0ki4Er+gGVpbTiakPp0eTCo5pgsteaR9WqGVTDA=,tag:xYzx5ir9aE9GBx01oQTfhA==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:oXzRSiCowUGlrXKuHklnigK42Wu9+djN0SjpLt9fWE9Bt7dfRE2/ntapin2Pw0ffKGHeOX0HQ4AaBW5weSegbF2d8pbM+aRAp88OyfW/0+mR,iv:DdVFCYjtzeRAgdktCHkOobBsO4x8K3krnJkjWNFfqfE=,tag:cUNPMXwvA5op725E6rjlhw==,type:str]
  RABBITMQ_URL: ENC[AES256_GCM,data:PvHXUBLsq5rmGPy4KRSnlF4bJ3zX0yRnhnAAaj63VFyCI/akhozMp14E7FtRUXKxXPH1Lx49irYlFkQitcjZiQAiV3C/Z9WV6ZinZvz2ZQJ/CiONhp8bqLNMy6w=,iv:8S51kMQqAHlyGTnvx52/uIKAO8DGi2P1jGr+YVr6nD8=,tag:FkHk1ipw2VmjSV5pGxnMUQ==,type:str]
  MINIO_URL: ENC[AES256_GCM,data:61wIJdTu72PIKkq3acm+NqOZ/ikQgR7m85s=,iv:mSQARlv1YInlOC72kls2zBo64mlm8lraCg7FeCjgSrA=,tag:R2Z0E2aasn0YxgPCxT4oeA==,type:str]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:mD8px9AHb2Si8c2UWzEJ8y8PMQY=,iv:dAoy9MT8c0vgZ9oQLD/Ky/SGYb/awMSYzY/iFTx2czw=,tag:eN6IaZDS/q8KzmdugAdQCg==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:ticgtGuG588hJqeQF7xU99g85DYeeMwwf0UpO+xSdbyob7TEXRBi8A==,iv:txLd61gufYn2xfg6tmfNNcpNUZPdPUkQ/idhmWDpYDc=,tag:sFDl9yNXGBggGeNLeDf0Ww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTU5FZnVPLzhHVlIwT3R3
        eGw4aHFoazRqR0oySzRPRTk5MWEzM1VIMmt3CnAvbkt4ajZPMnV3MWNWcURSdmNo
        NFFpMWl4OU84TFBJNXdEWGh1NlBiZ3cKLS0tIHcvMi9YbzFrV3VQTCtXNlRvTHEv
        WWowUno2ZVE3R29kb2JpeFZ1Ykd6ZTgKAGGXYCed/qenEvX+Oex31hGJT2lFEsXQ
        DeVj5uVaoTnIBWa3zbqhIRvw++o8hbzJLk5cPASYdbdg4ZgDp+ylnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-29T22:00:05Z"
  mac: ENC[AES256_GCM,data:aHKx3LP25IN7JkS9Xq+2xeXkkCcFBRpSxA7VtRNA0CcbppfUCKlzfd4xwdkl8GHJXKKtYyedRvJ9wgGHGkOz0F3kMEyGs0laEFd4O4+BTHVquNGeftR74R1aK5p2uXNaPWkKAJ9mpxZxEYhQ8/u6InR1R86JsOyjVfRBEVKqWjM=,iv:f+wNf2/Vzs+rv9CJJ8IRJCZmyy01Gz8csKh3XFi5W2c=,tag:oYRcHr70F4tTHQ/Rmnr0mQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
