# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: sonarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:rpE1OKVYtwRyczuvlLhbBGzc9xGPXczfAuATKPeBjd95GKvzVAk/pKLZDzU=,iv:HG93BmB4xllu906DkyYJoKRw/thnVl//tXMFQ4Dv9bI=,tag:BpvPoCtf4qm4qWvtgG3O0A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTlhjcy9WVS95YU1ra2Z4
        N0g1R05jWU9tb0JlLzRTSGdTYVhTSzhzVHpRCmNRSk44NExRTGMxMlV5VENIeEty
        YmdYRVZNRi9NQVVIcWZKR3Z4Y1RYSFEKLS0tIE5kSlpoR2tGdGZVcnpCZmhRUnBT
        MFRmM3NTa0llZUZwQ2ZFVlJTanpwZkkKe29CTcpltrnF84d64/N3n6PJJiml8eRA
        XxD6R8LarIScjxYEklXtA1SM3rPomU9XYG8sH/2FQM509H972r8G8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-10T05:11:25Z"
  mac: ENC[AES256_GCM,data:1WhyEH4wYHcV2GAl7Y3s3Y/LP++OSyyeN3pN/+UnVo6byjPLTTf/ZDcuJ36EmHNfOssJjwqqqkWwoKiJ4ir6TpyR1jn4j7nK3u6xKEB9Kc9k0ON/TB+3C1zQzIVlZvak/xyHEXRKDcyHZhc5jcR25UXBzV5CEXXlgU2ZkF8g/MY=,iv:nB/Q/0dtqtWZ8lfEc1sVNphXvDBwrrATflUqJ1/Ce6Y=,tag:ez+zAfTEkMo8OM8KP3DKOA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
