# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: sonarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:DihsFLdam67h7kgUtETo3A8BL6WxxW7+XhDB7UCLEUbGgfPUaeSpcvsbXDw=,iv:MMhvCQ8JoqDe8zYXLeHWZh0ZAL0Eq5HDHcdaTpuEx/0=,tag:vzqIs4X6EcgM8zjIeceENQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YmNrZDhoVUZlY1hucUl2
        OWY4QkVubXM0clFzdXFlSFI3TENUVXJGMGpBCnNVaXVlVFpFYWFPWGFyb0FNSEJi
        SjlNcWZBYzdNMEszT2I5USszZ0NmZGMKLS0tIGs1Q29yVVRYTERlZTRNMXNFSFAv
        UHRXbWQxNk9MS29Ka1B2d2VtVk95MVEKS90EU6YsCgYWoJCcPRNztDMROBzDrU1U
        2PqJTunnmyU5nhB5Mc2OE+QW18PCvS93YUwec4YZ/L8sAh+uzW601Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-10T15:45:28Z"
  mac: ENC[AES256_GCM,data:DjPgudzFZTtWo//vQBM/81algKGDePJm2fT24cTA/tnToUuLylHizgBpBKA8pBNIzJSd7IBGJxEMydgNniSA/MajccrDXHxewUnHf8nXOvYHQhB+iyHoyr0kf7NURiD91060KOHSPIJzpnqbn6aP2vzAxNCnD3pSuweJND0JmdE=,iv:PCDnThmR8PT3IWLn2lyiZg2scxNNru0cmd5bEQIrC/4=,tag:bCgjpj2HPczRDjK1bz0T+w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
