# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: sonarr-secret
stringData:
  api_key: ENC[AES256_GCM,data:jKqAcDYDvZK4yz8USx0sPCuiGQPuYyJXyOX4WIdxZ5Hv3NSHg/moHEFBxUc=,iv:dVwSrgtyX34/Cu4dq/RViesV+FjDMywV8O2PElAFxoE=,tag:Me/sCsT19lrG9SLQpY7UbQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YmNWSHZzSUJRS0d2NjVF
        djZ0dFRreHEvTW4rNWtuRjNadGpJcno5Wm5vCktzcHhYZ1NGY2xBWU0zVCtXSktP
        cFd4VWZVR2JobUxVRCtyaERmRWhsaTgKLS0tIEVoNVdzeDdzZHVrL1VMT0xNVW52
        NUEybjJ5U043NlhhSCtBKzBsc0VBNUkKM5mTDMlfGqCM8Hdc5qSmKqqhqraNbM5/
        LRTJh4Aeny6mG7J8ZHl9SpPZ/QVa11IHLg4Y1rOc/GfampDKJ8N4WQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-16T01:27:11Z"
  mac: ENC[AES256_GCM,data:X3si4DezbSGTSbLyzs7xzYeN8iZYSzJXbKn8YNQ8h+wt8lyyBcvd3IxL3szz46HRJBUu01J6q4pb/8ZmsD989YEJ+zISTOEFlk1afhbkKXxR7ZPjPnOD/mbcpPOWCOyCT6vQSKRQlbrh4Gv839hEPF9LJGSub6KI+KWeVAPyy1s=,iv:gjmyM+ayULwiKORKvIahqRiI6VSgsWfgRnw39PYdJcQ=,tag:nL+eOOSTR9DVXt+xpjn4ug==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
