---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app rabbitmq
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    persistence:
      storageClass: cluster-nvme
      size: 6Gi
    auth:
      username: *app
      existingPasswordSecret: rabbitmq-secret
      existingSecretPasswordKey: "RABBITMQ_PASSWORD"
    metrics:
      enabled: true
