# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: rabbitmq-secret
stringData:
  RABBITMQ_PASSWORD: ENC[AES256_GCM,data:sK2UkcCAXG7n/d2fp+skIAmot/EOpDCRYJn+9PNSsY4=,iv:6vmeRQlZ88ckih28P23nGJzVpW2BKLExx1wuKtXPubw=,tag:Hb5IISsrr9Nq3ziv/kV/EQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSW96N3M2aXpiL3pCOEli
        Z2VlaW9zZ2RWbDZtUW5BMDhrcTJBT2lEczFjCjJnUGJiNC93Z2dDdEV3UkFCejEr
        MDlrRlRBU3BZanE5Ymd3QktHbFFjTU0KLS0tIEJpYTl0TS9RbmxJc1NqZDV5bWFr
        cTFQZlNyRnJ3TW5IeTkydFlkMzNzNk0KEGlybL2SZO2SWkFFCZQLDBK7PtiIVcnY
        KiTgrJu/5ocSxBSHNx9800el/0X7WF+B26dNVOBn6qciTTa77Nvj4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-29T20:12:02Z"
  mac: ENC[AES256_GCM,data:zTmPD99kd/9feW6LRWxSvoUf5wf+2uUtuS2MhRjFq7VUL8aLs9p1/CwpTLhacR8p/0MoZSlO1rYU4suHwtIzFfKC/ZNlVaJhB+kiypcKE5YvkZDMH71iYeS4Zd3M9OwagMIZB7w80HwKxDdIOJ95DSDiKhUKRA/R85ibgKv7LfE=,iv:T4pYNJbM4WggnGu+dboEfP/fG3xdd6ksFbwZXWF6dRM=,tag:Luf8fpBpnTa2Wcxmv/E8Kg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
