---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-user-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cluster-user-secrets
    template:
      engineVersion: v2
      data:
        CNPG_BUCKET: "{{ .CNPG_BUCKET }}"
  data:
    - secretKey: CNPG_BUCKET
      remoteRef:
        key: "a87ff0cc-5d0d-4695-8bcd-b44a002192fa"
