---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  LETSENCRYPT_ENVIRONMENT: production
  CLUSTER_NAME: lianalabs

  CLUSTER_CIDR: "10.244.0.0/16"
  SERVICE_CIDR: "10.86.0.0/16"
  NODE_CIDR: "192.168.86.100/24"
  HOME_CIDR: "192.168.0.0/16"
  #VPN_CIDR: "10.200.0.0/24"
  #MGMT_CIDR: "10.99.100.0/24"

  #NFS_HOST: "10.28.20.10"
  #NFS_PATH: "/mnt/r720xd-nvme/r720xd-nfs"
  #NFS_MEDIA: "/mnt/r720xd-array/r720xd-media"

  LB_TRAEFIK: "192.168.86.180"
  LB_TRAEFIK_EXTERNAL: "192.168.86.181"
  LB_POSTGRES: "192.168.86.182"
  LB_MINECRAFT: "192.168.86.183"
  LB_MYSQL: "192.168.86.184"
