apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:a3Rz/JRutnIjGh3qIaIT,iv:yxJm3cDolZDsbqoEyH7+PNu6XBi59Oe7iXjR0ZZDbD0=,tag:SUm0xzUULjURVAvuOnS1MQ==,type:str]
  SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:m/vbbMUJAjf6D26SLBrnvQ==,iv:Bs4+Kmir1Ob7SFGqoI4/QU6hpk1zB37HzAC4tHzG+kg=,tag:rgRSnYTSJGzUxQvY/AtjUA==,type:str]
  SECRET_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:PAOwC4zI/AY3gg==,iv:rTvhixaykS7GF1zvaHTSvCV4jhKqsdT8YomOpSzeO0c=,tag:MYqjS10p0ydBXCX1/q6R4w==,type:str]
  SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:rBIWYosu84vGYsFEMxmG,iv:tTemYl/rEuT3Ml13XlDyPz+VB9B5eRTsAHUiNUH5I3g=,tag:MkIxpS65VCyuBQlHV/14ew==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:SJ/JDTJdPS+9rQ==,iv:nUMVDZfC3hSKaoxzdhq18UsY7d3qhb0bEwCvRQGc+is=,tag:OvJB2qk+A0y07/zwo/5HlA==,type:str]
  PUBLIC_DOMAIN: ENC[AES256_GCM,data:379SgUl6BcgBXwKg,iv:IrG2yPoWbuJrrfPc6p0dt1CE05PsC//YiyPxoplFYNQ=,tag:HZOT/38FV4NCxkqct/UjmQ==,type:str]
  SECRET_SMTP_FROM: ENC[AES256_GCM,data:vqcWO57QD/sOxj/vsk9roTcJVE7P+c/z7uHV0GI=,iv:812KjvqZB81S+ghLvOaHmzEA78Eah9+4ySHE2NmY4tg=,tag:Z+zhaFqjYCKQiZMkiniPoA==,type:str]
  SECRET_SMTP_HOST: ENC[AES256_GCM,data:03u+8qxb9KqJmHS7PJYDvA==,iv:XMi9gsgZJdWCnv22kfxgbidumA2bROLjykIdl4xCfSw=,tag:GQgK2Qa5Ls00jkrvGeaaxQ==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yXcdbuQF8TdKugLsYtP/lc8P0VSrq0ClwyCDD1W6PkOT+1IU,iv:kKlzFKtPIhybteIM3ZZJgYOVuf9fzRziBc5GPFqKzEE=,tag:FRnpb0mZH/TRaklkYjIv2w==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHZhYXlRU040d3psMjRJ
        SEhtaHk4bXlCanVIdlVkVUF4eitHekdac2s0Ckk2a3dLQmxqRThuM3J6Rm1ESEcv
        U1JjN0w2c2NZTVFjaDU5YWtFTWlvekUKLS0tIHVJMk5qVHBxd2JKbnc5NDlsOUVk
        bVlGeURZaWhZSjYwTnJFcWljUzRSVTQKJkQtMD1F4ieQhGGcI4WHCHxVmbREgGLb
        q/mQ1k5g67FcQ42il99uTXY8sWEtNcwAY079Nf5+SqvlDfJXFnuRdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-14T00:50:38Z"
  mac: ENC[AES256_GCM,data:TwITuruHx/TRH02DQKtrojazrQWShPE1rrt3/hLifhl/Z9Klr1qCgWX5rNIWpBufklasapz/hGRLPJ2TJ0Ed+M32dEeyPVunWIIvr9q7smE5a7VMtk1EsXr5olakYluZkSdCqaPZ7PCkD4cIuKFfnGOx65IMySexh2j3VYnmVTs=,iv:V1WIh4f/T8NOmdQpO1BwCrC4h8JQzWX1dD6FkGnv7Kw=,tag:lWRo+vvs5tde5VOjzOtVSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
