---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  LETSENCRYPT_ENVIRONMENT: production
  CLUSTER_NAME: lianalabs

  CLUSTER_CIDR: "10.244.0.0/16"
  SERVICE_CIDR: "10.86.0.0/16"
  NODE_CIDR: "172.16.4.0/22"
  HOME_CIDR: "172.16.0.0/22"
  #VPN_CIDR: "172.16.60.0/24"
  #MGMT_CIDR: "172.16.99.0/24"

  #NFS_HOST: "10.28.20.10"
  #NFS_PATH: "/mnt/r720xd-nvme/r720xd-nfs"
  #NFS_MEDIA: "/mnt/r720xd-array/r720xd-media"

  LB_TRAEFIK: "172.16.5.10"
  LB_TRAEFIK_EXTERNAL: "172.16.5.11"
  LB_POSTGRES: "172.16.5.12"
  LB_MINECRAFT: "172.16.5.13"
  LB_MYSQL: "172.16.5.14"
