apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:H5w89aiNATwU2Z7oof6v0YYk9yYAr5P/fN3JuUg07qx3CQkdZRd7aQ==,iv:DZQCIXGlGzkGm8T9xjWQ5wpRNbwMs0Ufwfd1P4GhJ8E=,tag:0JRQWynJWoWGw0N+fqzCiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVURDTUZsRjZEbGVWdnZn
        SjE4M2dOc2J5ZW1nNGxHZlkzb1VLTEVuL20wCjFtWDh2UWo0VWgxK3d3QUF1WTlr
        bWNVeVJqK3BhLytsL08yeE50TVpYZXMKLS0tIHZZVDZjVEtZb1VnT3k4b0lsZ1Zx
        ZXpVbXhZWW90b0RKaUJyRmEvdUUxemMKbwQNH6WHvSnPa2VtjREFRLJZ8TsqnE1k
        T8iPGcAddNH4Wf2QPjwJt1Sr0AhY0kTyG1bv00EKGF4eQjt5RRj+pQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-09T03:13:44Z"
  mac: ENC[AES256_GCM,data:+wUROJ7Gd/ZPR0K416Rj86HJdTihRnFZsIguI5a42tiAzNH+J6F3ZHawNglDDhzFkLwXq6DpBk3daS93yvJdJyaFxCyv317jDv2sRArs6Vzh29YPRp8CwYvLJbjzM36goDJvWhVUHab0TzZq9WK+jWf5DWCGdpfNFCfYXtE5a4I=,iv:UTDj+PkcHJff/QqMGjsmqv0i7MmKEFoUPpZBhImUNH0=,tag:poEBBtTzVHRt8b1cI93JSw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
