---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mataroa
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mataroa:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            # https://github.com/onedr0p/containers/blob/main/apps/postgres-init/entrypoint.sh
            env:
              INIT_POSTGRES_HOST: &dbHost postgres-1-rw.database.svc.cluster.local
              INIT_POSTGRES_DBNAME: &dbName mataroa
              INIT_POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: &secret mataroa-secret
                    key: PGUSER
              INIT_POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: PGPASSWORD
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: cloudnative-pg-secret
                    key: password

        containers:
          app:
            image:
              repository: ghcr.io/liana64/mataroa
              tag: rolling@sha256:702eae37414c0b492b766771a50b9c8490b4a34259699eae3a7bdf284f2abad6
            env:
              DEBUG: 1
              DATABASE_URL: "postgres://${PGUSER}:${PGPASSWORD}@mataroa:5432/mataroa"
            envFrom:
              - secretRef:
                  name: *secret
            resources:
              requests:
                cpu: 12m
                memory: 512M
              limits:
                cpu: "4"
                memory: 4Gi

    service:
      app:
        controller: mataroa
        ports:
          http:
            port: 8000

    ingress:
      app:
        className: traefik-external
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Mataroa
          gethomepage.dev/description: Blog
          gethomepage.dev/icon: mataroa
        hosts:
          - host: &host "${SECRET_EXTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: mataroa-tls
            hosts: [*host]
