---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./loki/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./changedetection/ks.yaml
  - ./blackbox-exporter/ks.yaml
  #- ./gatus/ks.yaml
