# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: atuin-secret
stringData:
  ATUIN_DB_URI: ENC[AES256_GCM,data:m5pgneHGcBCRjYQK68906Rq69pF0PUTjIcDsBHtKpl2MEZ8NP8XhRkbmJU8DLXB/ZSH+7FSz+UZyyXJdxIbcTXpUMDKNtMfDopuIexR4dzCaDxL0wwoP9w==,iv:doqFwXLkl1allRxFqqi1cOCWxNAX6qOE2DGvENRaXOE=,tag:W6FFOecM9w/A4w1u1yWVhw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:t4E8sAI=,iv:6Ft/W7f0H6aoDIxcW9pkn6qGsvgd+yU9eb8gOI5sqyU=,tag:tNovKQVfZdocrTiQzz2/Bw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:zmvnFrd4sjb+4CU8T/FsztnUmwDbA/tq3rMfNQ==,iv:V0vISbn9ztfOeaUXtf99By2qfokhITyerwy9dDbmSzk=,tag:W6UKOSpEaHO+/cGIStDblQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaGEwNXBKK01EbmIrckE3
        NGFPUkVUbnZVR0x5bU15S3U3N1FNeUh5S2g4CmZwOGhLc284dXBWODhJVzVXM0Rw
        THZhOHBCNjFZU1BaSlBLTjI5VzcyQUEKLS0tIExZM2tLR2xWaVQ0OCs2TzVYVVVj
        cTZNZlJyNHFna01uWkN4TW4vZWlsR3cKak4UN5+NUbAxC7KwQ+fsLQRvRFw9Btoo
        D0/r9vx6YqGqtzRaUtZAw7YNbnr+zkcVPKLt2z+2lXERLongxzOp0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T02:17:53Z"
  mac: ENC[AES256_GCM,data:obi5FSnACkZswoQWUrgdU14WTm9lZ2SR/m4vL/HruBYYs5EjBEfTHvGpDwR0JcxJ/DIfs6hnlu7ulHPuV92Ho4wSgmtK4E9jgl2mkG+CrIrlP9VVjcB+Nv8EaTji23wAgt7dHSxCowk5itEu0VxmYM7rrXeULmxSB4ECeztOB1E=,iv:WrKucLQiffRMkU5gJ6/RiyhizTzsEhfKO3zMwJ/TYN0=,tag:E6IKUl8bH6b539OuPAV9NQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
