---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app echo-server
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/lianalabs/apps/observability/echo-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
