---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bitwarden.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./descheduler.yaml
  - ./grafana.yaml
  - ./itzg.yaml
  - ./jetstack.yaml
  - ./k8tz.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./nvidia-device-plugin.yaml
  - ./openebs.yaml
  - ./piped.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./teleport.yaml
  - ./traefik.yaml
  - ./windmill.yaml
