---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${VOLSYNC_PVC}"
  trigger:
    schedule: "0 */12 * * *"
  kopia:
    copyMethod: "${VOLSYNC_COPYMETHOD:=Direct}"
    compression: zstd-fastest
    moverSecurityContext:
      runAsUser: "${VOLSYNC_UID:=1000}"
      runAsGroup: "${VOLSYNC_GID:=1000}"
      fsGroup: "${VOLSYNC_GID:=1000}"
    parallelism: 2
    repository: "${APP}-volsync-secret"
    retain:
      hourly: 24
      daily: 7
