---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kubernetes-schemas
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      kubernetes-schemas:
        containers:
          app:
            image:
              repository: ghcr.io/budimanjojo/kubernetes-schemas-web
              tag: latest@sha256:6798cb1435f9928d93398b5ea00c6dd5ecc0aae0889278e17db1fa1b14117b5b
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                cpu: 200m
                memory: 128Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Kubernetes Schemas
          gethomepage.dev/group: Tools
          gethomepage.dev/icon: mdi-file-document
        hosts:
          - host: &host "k8s.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: "{{ .Release.Name }}-secret"
            hosts: [*host]
