apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:N6h94R3HK8iBRy7QLS3X,iv:y9kU03w67sttM/tRFbZikfCXRKRT6mi4kny3Rw2HDbE=,tag:s/sowx5DSIeRC486tMNu+g==,type:str]
  SECRET_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:mZv/htNt/UWXfw==,iv:pb25PlnUm+jMfMV3WUALf++xJ1rUkoRkEU0ZOPkkkoU=,tag:FtcFaGWukHNuL/dDH5ujFA==,type:str]
  SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:ArwYCSLbnNutj6e4AElN,iv:TX18r74BF+Ny1gQVdOhS4LVIGkrXfMC4xDjLZCcN/lc=,tag:10xdjx1p5st+dCuPK0vL+w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZFRIZHgvMWJUTTVUdVc2
        a3FsL2xYQXd3NS9xTU9xVVlHVHQwWjNnRURFCi9qa2UxVlo5cm1HWUoyQVI2Qk8z
        S2VwN0lsdzNhcFREQThtNVg3WHA2QUEKLS0tIDlaalZPeGNyT1puNHpoWFpxZ3pz
        V0o0WUJqZnhyMThYZHhhb3FzS0dpVGcKkqpd6LdYK7VhcGODhLG227OIxFIYN3BZ
        21Q8ICdXfWYUwKmHE44pi7mC3f1A+6cdSFRMNofmXp0vYTgjKXgC8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-09T03:13:45Z"
  mac: ENC[AES256_GCM,data:+jUSrNNSD+OBm+zwDdld8CX32P1KqXx9H/Vk0/TMKy+xVi8OrpkGL16e9QEPCO3zftXgXI3Hs06kV6qVJ6KSfjj5zH5jyyIqckQAaVOPgWs8lUpNwHnPhIVs1/lghjwEZF+VGZncaIJZ2+kNyGqHTMTL7kb5vkS7qOQ8q7aDWQE=,iv:ICkwYKeT3O5MPT+8sv9hXNpCKJJVNZ96Ji/NsjFCOKU=,tag:5Gshf8Lx3loDeVS5AxVO5Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
