---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  LETSENCRYPT_ENVIRONMENT: production
  CLUSTER_NAME: lianalabs
  NFS_HOST: 10.28.20.10
  NFS_PATH: /r720xd-nfs

  LB_TRAEFIK: 10.28.12.100
  LB_POSTGRES: 10.28.12.101
