# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:+OXZcv/saxs=,iv:Xa7i/EzlO9Mdp7XVoh4M7lvrjqVkMnytR4ZjEFc0zT0=,tag:rQL5ta1W7AvC00egR5rZDw==,type:str]
  HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:KiITgqjCzUtL,iv:bJzB2ooYEA1F6ZkTQuq4oI/52jvar0xUcoSKVUGA1M4=,tag:2iA1tdp4qZuU5gzr9fJIAA==,type:str]
  OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:uVwEuwZ/dXVh8s0cG5kdf9yIoWUwRM8NMgMK26iQ3A==,iv:AZmxlaVbEzBOzqtjYVX57EJGSsOnTne6Viwoh9HLQz4=,tag:qkHjuZMPk0Pt8PawcyNufA==,type:str]
  bookmarks.yaml: ENC[AES256_GCM,data:gJ8eKlgKRD85lv8BBJJrD/VAe6Fg5WPFRoL9cCawXqDtkvIk5v3vZiLAKerwOCB2DhWGKDxYClGII6LAy7L7wYmjYPZWMEHWSQjB4XcYv2cq8aMfOn85A2lLp0l3CEBoXMO4L4b5+ihXz95OHultv/2WZY8sKsHeEf3Cam+P1Ya35nO/UCC7ynAnc0nmPvG02h73CJvP0v01+0aFdZL04B6D8rPLSqb7AOp/Xpky6Ws0ecTSFjd4Q3nA2XZwHkmhLEppP7o/TrTRhbA/qbIpuvhAMlSmrpbcQ03KL8W0Tg5Vg5GztBXXyxMbZfmPils64jZUKG9f3SYQMmlurLAJi+Pl5plXOJ2Xz2IjysStl7LfgxYrJrhAXvAPHdXK0i89QIqt1wR+21vz0q2bni1KnwjwyTH4b0NxUb3cp+fVx/qnYMrAb9dBV9gNwblY+SyO/rZMjbt/vGSJnoJR+8RdHanZXWcQImdArYnn6l3CNOBo8OuPMN84vG0UzS1LTqfHciFfWfXjFDNUMMSlKQjZBmQNIKAJZtwhScXloozXl7cdXcqKjB+YrdH8LSR54nWVM/Ae+XhnxUG1yidqLAmG4+XiKatvAmL0sjxaiuNyS5q3efogW7v2GoT0kYFfXhxI6Vp09ayDucOJ1rpIx1wFkoEIXjC2sm5Np2xY5ZUpRQZQzM4Davac2PRzgHo5B1JBAOha9hLEzjKYzM3FsH9OF3f+TGinxIJWBVLhXGSb4M1AJy+PTAfDHLYfLrcFEC/622zX8R3B1L6yqZqqTooD6F51433Fs2z5OqigEYT5TVbQn1BEm3KqsxsmA8q7ZQj35ZFO8Jy/OwVClapscVf/kabE8bSPJ9OMmIqBWhE5pElP7UNij7jSt0c20id07f+9mae1e9Iq6rMe74aWCTsWHZo7labpqw7BXg==,iv:AKg+5H9CjHBOMeGZKQBE3KETVKEDykqO9yRAdRi3qrY=,tag:zqfGydIhn6yj7dSXrkcOTw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y2V4bDZncEJOempPWkRt
        RTF0Y0dnMFlSSlJjeTVUclUraDA0QWJ0SndzCjNWajZ5UWE4dUZwZFo0WlBwWUN2
        SHN2YWFRSi84QUhiOTc4WFNBSWdBMGsKLS0tIFlnQW9VWTJETHlnTnUwQWNycFZq
        aGgrOXF4c2hvU3AzVHYydmgwNndCcFkKjPeLdIRcnd451sqnT9O6dLBf/HGM+uHX
        UU0yvGCLz12dMgJEQL8m8phUV4gzXTC8owJLZkGHc1nmz/wd9qXNRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-09T05:35:53Z"
  mac: ENC[AES256_GCM,data:91Mnhssi4yFbnr2wwqHx4pXl2OhNHAdG+3NkvnUyOLjLkEIgKXT1u2LaEgJPyAOPqquqO17m/qy2ZhDyFqsBeSFZFOMht6oVyPop21OhnTewhwPavPqYAxj+jw8Zgu9Wb3/zRSc5jj+JbOB6WG5KLsOtdCG4G+ka3vdWrBRdVgA=,iv:l3+7zmqDAkSScJ7v+hM0p/0RnVmtsgqr4Bj7MmhVaUU=,tag:VNN7J/p4aZ3DRBITQgQnvg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
