# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: pgadmin-secret
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:rJ5+iidR/DLqxHkqC8YOIQ==,iv:XEJCBGIDAr5OGtxZeEVSYZojv7XkOS/5XwKtCwtA0V4=,tag:qWkdlSZsF8bTpXkbgfvsyA==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:a/CLhV0PWiYHS8QN6RTOtFYY7d1OXcx8oMgS2Q==,iv:/9QldsctDUmtSBsA2KrqlVOW/sXJGu2FZb/Ft3tDJ0Y=,tag:kSp32dB9ydcD9cgMf00H0Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZ3JzWjhlOVBic2NjVDY1
        a3o0MjlGbkJrTzdOWThmUUdPY2VHaDgvSVVRCkZuTHZiMUZsTDVSc0ZEaXp1ejFp
        VXVhdmsvUFlIcHFWOVB4cm9GTzhrVG8KLS0tIDZITGtiMW9XUm5ZeVY0YlhPMXIz
        NmV1ZTlxZENrTDZZWUtKWFdWeURVQ0UKcbsGBn2umnLc8RINnaPO4xoB8J445XTx
        Ir+6mSoeH3ZkmLLezucj1bWLPAXdsl6aMwrHSsonALUu7nrV9avsPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-09T03:13:45Z"
  mac: ENC[AES256_GCM,data:r/qL+gIhHKTHz0OIm54TrrEHP7tHyw/Xb00jD8N86d+p5i2bQREpefaqvqYIf7By5eL8nCxXN31cU+njfAe6beoT9CH/oivGTWgiy9gnkx5Lf4a4dNpQ1uhzgW194l6L/Rw6KE1DeYCNUCXVbDz/Omq5ksS6m9rIuSkiq7PVWQ8=,iv:cvtOunBcGMdShFEA2kLEleacOYkUnjTJ3GGKc7xUt6I=,tag:wfAamN3PZq+afoSA2gvBlw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
