---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
data:
  app.ini: |
    APP_NAME = Forgejo
    RUN_USER = git
    RUN_MODE = prod
    WORK_PATH = /data

    [server]
    PROTOCOL = http
    DOMAIN = git.${SECRET_DOMAIN}
    ROOT_URL = https://git.${SECRET_DOMAIN}
    HTTP_PORT = 3000
    DISABLE_SSH = false
    START_SSH_SERVER = true
    SSH_DOMAIN = git.${SECRET_DOMAIN}
    SSH_PORT = 22
    SSH_LISTEN_PORT = 2222
    LFS_START_SERVER = true
    OFFLINE_MODE = true

    [database]
    DB_TYPE = postgres
    HOST = postgres-1-rw.database.svc.cluster.local:5432
    NAME = forgejo
    USER = forgejo
    SSL_MODE = disable
    LOG_SQL = false

    [repository]
    ROOT = /data/git/repositories
    DEFAULT_BRANCH = main

    [service]
    DISABLE_REGISTRATION = false
    REQUIRE_SIGNIN_VIEW = true
    REGISTER_EMAIL_CONFIRM = false
    ENABLE_NOTIFY_MAIL = false
    DEFAULT_KEEP_EMAIL_PRIVATE = true
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING = true
    NO_REPLY_ADDRESS = noreply.${SECRET_DOMAIN}

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

    [session]
    PROVIDER = file

    [log]
    MODE = console
    LEVEL = info
    ROUTER = console

    [metrics]
    ENABLED = true

    [security]
    INSTALL_LOCK = true
    PASSWORD_HASH_ALGO = argon2

    [indexer]
    REPO_INDEXER_ENABLED = true
    ISSUE_INDEXER_TYPE = bleve

    [cron]
    ENABLED = true

    [packages]
    ENABLED = true

    [actions]
    ENABLED = false
