apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
type: Opaque
stringData:
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:36+qpwWj3g==,iv:ctyzlZvDG3rnA7Zpkn45V3tAWxsdBNveMD7IfFM665Q=,tag:FHKL4UaII91WHlPMfshvVA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:YhGrSCep5sQHKedgFf/1VkI39LGAHSgd2a/abNgooK7tiPhvrHpR0mXzVpnFSCSR,iv:RKwgu98pz0CXGmSc+ncpWn6fcg4S2juJF65f3YXxv6o=,tag:YHPuksTBsbD1YtyG30pDnQ==,type:str]
  FORGEJO__database__PASSWD: ENC[AES256_GCM,data:4t2L5f+NO0q6hX2IZyWeN3mzu4s/aeaBg1Ttqwx1AwUC1znF/7k26EVtsi6qxtjH,iv:wZSZAqOAQPWXBTLdfXvrBwz4YhrHTVEe0rThhR81qhY=,tag:IFvyMie1Voc4zW+uo4WQoQ==,type:str]
  FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:m1d8mC5I/K2zZ5rackPaffsa41AF51p7pZ7QnWytFGJku1vosS7Iz0yB4qEqn6q2P8TEthNabnrMxCLspTu9wA==,iv:UB4ozLPbpQlqIBYkAtKtn9OA4W0aGeEhlErdDr/02/c=,tag:y/0rR16ijYFMJfBPsKN7Jw==,type:str]
  FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:swn7UcOo+0KMIC1pckzh87NBAmi8JzbPtpSJvgSmmXBhibBABJlXA6HIB+VKJ5a4UGEI6eX0PZG+ozbOb2RgZ6c6meZ2E40yWBP4w75jyuParjnuKiUjr/wDUxdNXymc+hW2khEQoyrLskdwT+o5rosjnVPDusxz4xCjynKEwQ8=,iv:4wrw/aC1LqDEvGnVn10KBdLpEoTUmDge+zYnq5d6vow=,tag:ePvjXEI/BdI5fis/VA6KjQ==,type:str]
  FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:0zqvmKocRk1OFRE+FDTCxviwOlOfTrepS2yIW3sEPCj34CO/8CeW5vHWMw==,iv:XS3hR/RxwRi6ZN3c601GL8xiDg1iUrpLOQjGfh2UEJ4=,tag:j8S5kwwR/Ti4YPW+JcBq5A==,type:str]
  FORGEJO__server__LFS_JWT_SECRET: ENC[AES256_GCM,data:iXC2RgNb2y+TlI1/eAJJNdEIQAThw7BNVu5Id3FfGwLCwsPLokNEKbxDIQ==,iv:+KaiZV05qBuA7xL+3RXkt5GfvpGJbf3ZrtgKubMUl4I=,tag:TLVX0IVgBOM1ARSkn77KGw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY1Vjdk1FZm5lNHExdVdj
        R1N0Rmt0Sml6ajlrbFowd2YyMnIvdWlZalI0CnQyV2Y0ZERXV2E1U1FzTDNBT0hP
        Qkw4VlkxU3dCaWo2dlMxOG5TMUllOW8KLS0tIGl0aFhPTjJpVzFqa0RWSDRoTDFm
        SUcyT0lFb0orRTNhV1V0N29DbnVnQW8KK62uOrHa89YYs9oCmsRbqXtqTjusRjET
        VS3mzuAGFi7hs8GXVR8qG2KBG4NXZzeK7uCCYqQi2Vt8rSSLw0yPhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-13T01:28:00Z"
  mac: ENC[AES256_GCM,data:dHFmcqNKq8Yxayxnk/AiDQYRWcPCt/A07qk26uHZbnPInz6h2NO4sA00LAsRuCIBcVG5WVjY9PiH2P+6bLG2oY/4o66cwBXSFTf00uFUZNZTJIUPjxiiLTkQpAa32vQ0TY4t6IFriKY8seZaDEpU0cPtf0tRrcyMb+UWC9LJApA=,iv:jxdLvWmbJh0uOXZBkFjLNnnnDQiLTEsEggDygaKL4So=,tag:cKgKaNJXF1ImKm2CqxVy0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
