---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mysql
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: github
    controllers:
      mysql:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          mysql:
            image:
              repository: ghcr.io/linuxserver/mariadb
              tag: 10.11.10
            env:
              PUID: "1000"
              PGID: "1000"
              MYSQL_ROOT_PASSWORD: password
    service:
      mysql:
        controller: mysql
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${LB_MYSQL}"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_EXTERNAL_DOMAIN}"
        ports:
          mysql:
            port: 3306
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 8Gi
        retain: true
        globalMounts:
          - path: /config
