# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mysql-secret
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:itJLu2+bK6F4039pm+ygnm+4lXySO6oaF6E0PymgVljNxFOSQBX4iYVjc0P0ogxaseATaSPGFww=,iv:UmLA+Y+N9UPksuL70R/MWRsTNsqCuzmBK1UIMQ2s7v4=,tag:C9cukU/Daqkd4cI8rO3fBA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb1Q3THBzTnBNSUJDN3ky
        dEFCeTlJWkFvMWFnV092ZmZ3ZG1PbEg4b1ZjCm9wK0s4ekdJK0VSaU5FQUdJdjdp
        dmppZytiRThhQUhhU2JiYVVDTSthTjgKLS0tIEJFeHlIdGJFM1pJL042WEsrL1pp
        SFlGZDcyNDQyR084bC9XYTBGRjMrYkEK0z0CF6EZPd8cniJTtCZNy26wRYXUs13c
        F2wPUaGydg88EsYNaQYx6unQVj0QgwN5wgLpAh/Y0SnNXFetS2jkNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-24T05:03:04Z"
  mac: ENC[AES256_GCM,data:sbyMYCS+X+h2hJEQYV5S47IZ7qk8YxK20aCWEU7WkcSZP7kMvbxjhyptpoMeihU3PFbQjBLveYxWF2hdsUY/p1WZ3rihLSD5QluMhtn5ha0CZIj8B21aLtHohVq5QUI0Os5a4rxWfh3/rI8ayuS/zcbtAouFkV05cPZ8z2vu7W0=,iv:6baoBg2UyvrXjrxHM6klGcxm5ze3j/0mhT46ca8UpUM=,tag:NXek+0VfPz2T9GSztheOtw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
