---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pingvin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      pingvin:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: stonith404/pingvin-share
              tag: v1.5.0@sha256:6ab8c404a24a48767ba73955bc9b4c44e48307a39aab8ea74ddf351de0f2e280
            env:
              TRUST_PROXY: true
            resources:
              requests:
                cpu: 5m
                memory: 50M
              limits:
                memory: 250M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
          backend:
            port: 8080
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Pingvin
          gethomepage.dev/description: File share
          gethomepage.dev/icon: pingvin
        hosts:
          - host: &host "share.${SECRET_EXTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "pingvin-tls"
      external:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "share.${SECRET_EXTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "pingvin-external-tls"
    persistence:
      data:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 32Gi
        globalMounts:
          - path: /opt/app/backend/data
          - path: /opt/app/frontend/public/img
