---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
  spec:
    virtualRouters:
      - localASN: 64801
        exportPodCIDR: true
        neighbors:
          - peerAddress: "10.0.0.1"
            peerASN: 64800
            eBGPMultihopTTL: 10
            connectRetryTimeSeconds: 120
            holdTimeSeconds: 90
            keepAliveTimeSeconds: 30
            gracefulRestart:
              enabled: true
              restartTimeSeconds: 120
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp-pool
  spec:
    allowFirstLastIPs: "Yes"
    cidrs:
      - cidr: 172.28.0.0/24
