# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: prowlarr-secret
stringData:
  API_KEY: ENC[AES256_GCM,data:5wzcM0WIHaUAWdo2oD2o0VA1xmW254yGIPbBs4IOvUdeLqMgvrQeELs7oFS9OSLP,iv:BdGNl7zWRm06Fi6oadjCcxwjWBr8egl6GerLx7JWq4g=,tag:leaytQdTWoRb7OJ8oMHM+w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UGpkMUN3ZzNtVjJlcUJV
        QU0wd05Xci9ydEZGbW1zMHBsNHV1ZUloZUdFCjVDMHdnMVF1bTZMYUc2Y0ZSUDFm
        T2pqT0k4QUJIY3ZsZVVtcy9DNmYzSmMKLS0tIHIyanNSZmtkVkNrejhTaERaakJr
        c1VKTWZJVUNPOFZUNjJ0eFpIMEYvNDQKtOOLotFwvPsq+dDgkIYzwNblHSoEYEi/
        SSAzf32ufxFQRAEzIkIIwc7GKpcKkhF+8CoG+c/JE9VUeJ0+tty1Pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-09T21:41:45Z"
  mac: ENC[AES256_GCM,data:otC8H0PW9z1xNQfovLiQkzckWK5Pe26wDwSKk+B95NEvv9CjzZrYkHg7L03dP9EHBHB2uiEGexCi4Tq5Zrs+1r39II71NC3YinI14K4318yAMxWTzzbWy8jeUrvXXVbxEem7JIh3+foIqcbmMtb+VmO2fyzoB0ztByiSUTrfPnU=,iv:dDkPerAall8Ltub1RG4ubhg1cqPiPzA4MHSGIlRHCwA=,tag:fG+JRMuE6RlfImG3G8H6Nw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
