# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: prowlarr-secret
stringData:
  API_KEY: ENC[AES256_GCM,data:3uj8j4U/UE3sF24NhaogvUOz1gFkjVZeX0d4IQQihEs=,iv:qklcOdRll6clgcVccLE7L4el31aOl1qToZPRkeWMpgU=,tag:LIrB555zX/EY7KXsDOJyow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QlVhWXJnVEUyN0hTbFVO
        eVJCWk9aYzIrcC9LcUNNOHVyRDZWTjdVVmdZCnBqWlJoZUZLdGZTdXg1emlTeWFM
        UHdVWE50S3VPTklxOHRHZjlXUTlORTQKLS0tIHlMeW9VWnBFeTIyM3I4QnlsbFdQ
        M3hXVklGUWhVSEdkbWdWOUJiS1RpQ0UKI/HPah2WCDhQZbD4bhGTLbWHfDdtdTPC
        qfRVxSNBF/g7zPGWIRI0ujA/lh87OGjb4vM6dn5kFltR/plLz2g/jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-10T05:47:36Z"
  mac: ENC[AES256_GCM,data:bb2QRSkFZxuiPve8RkfhJn4cfdA8t4v2wi5n8I6GOt+MNxHoG9UeRWyPhs2CszPyZh0qrFBGxhAOrFEIaJt24Jq57hhBurllFck3WUHHC9aE/I0ArQMtwELxg88BDhFreeWuxCCyx5vLYfyKbjwUtoDuDQ5nJTfaLfwdBqk+JKE=,iv:JPBp8GMJMNqlc4matmMaNwukktmB5kvh8NvMh1oh9YE=,tag:gH4P1Dt1fxIGqJBI+alx1w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
