---
# ansible_host is synced from `tofu output -raw ipv4_address` by
# `task ansible:sync-inventory` after tofu:provision.
all:
  children:
    #edge:
    #  hosts:
    #    infra-edge:
    #      ansible_host: 0.0.0.0
    #      ansible_user: edge-admin
    proxmox:
      hosts:
        n2:
          ansible_host: n2.lianas.org
        n3:
          ansible_host: n3.lianas.org
        #ms-01:
        #  ansible_host: ms-01.lianas.org
