---
title: Dashboard
theme: dark
color: zinc
headerStyle: boxedWidgets
providers:
  openweathermap: "{{OPENWEATHERMAP_API_KEY}}"
layout:
  Network:
    tab: Main
    style: row
    columns: 4
  Observability:
    tab: Main
  Services:
    tab: Main
  Production:
    tab: Main
  Endpoints:
    tab: Admin
  IPMIs:
    tab: Admin
  Hypervisors:
    tab: Admin
  Backups:
    tab: Admin
  Downloads:
    tab: Media
    style: row
    columns: 4
  Media:
    tab: Media
    style: row
    columns: 4
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
