---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app speedtest-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/observability/speedtest-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
