# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:teu5Iya1hz4=,iv:CXabbI8kVv2X4uoYb7QBq5OOnLlP9EPRyc00rG1UU68=,tag:NlyaiMHCmazmS5l4w4ewGA==,type:str]
  HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:JOB3jKdcTeIk,iv:dKyXV/lq1PDaC88t2Dva41XE4dF+w0J1v18BCMB4sBU=,tag:hwyzS9g91J7qeGxzzOS2cw==,type:str]
  HOMEPAGE_VAR_OPNSENSE_API_KEY: ENC[AES256_GCM,data:xSj1O6znu2YyRNUo+aVdjWIR+4ODeA92ZtiA5VENY8GJczzF27vDXcOMSsLMUHmvFEFBdSxJSRIX+SghgnVxEtl6N5moMfYgAf/OR69Dm3g=,iv:PCwX8Gwc19xgfhaRKtD5l4d6fZaE7mgsTGKmyd7ICKE=,tag:ORBR41NJF2Gb7CnO04GrRA==,type:str]
  HOMEPAGE_VAR_OPNSENSE_API_SECRET: ENC[AES256_GCM,data:Awa7d1YjadmYV1EH8hmkyQzUxOue3mQEj7A7ZIQesjH6TXxrc483/vWg6N2Gjaat73i5dPY7gd6XirxqDL9GpTjJ8kPnHl9a/EFyelV/tDI=,iv:wEhpovpIii0hfqe0ThIomlqWaPltKu9zGzKT8BESTkE=,tag:eT8wivNLmgMYeSXfomNr+Q==,type:str]
  HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:ZuoFl6hao96WU/tErmEuKX2dyejiiZ1WubZCIEizJyg=,iv:9+0nsjUlAplvreL7SgdzsbKjWWgXz4PPJDiiVVVtMOQ=,tag:3djuZ5Pr2s3rk3n4hGWO9g==,type:str]
  HOMEPAGE_VAR_JELLYSEERR_API_KEY: ENC[AES256_GCM,data:xa1Oe2ppsLNDbCTFKqBJc3K+7GjvyTdvmZ/xrVehwE7/vXGHCzpTPsgzeAOtTWiHuqmG//e9G2pVjgPUOTr+Ps44qd0=,iv:bM8Q2PCzwocgh7JtIWeZSFv/T5XAORXbrpaUB8EjwS8=,tag:90NyPW0gNSclBNbwfR8t0Q==,type:str]
  HOMEPAGE_VAR_MINIFLUX_TOKEN: ENC[AES256_GCM,data:5yoOUHqyoucxokJO+Xm4ovi8dIo6t0ZM6i3YpmOEH1q7iMn/wMjo1JsZqw==,iv:6hZ91KDKzHp19fJT2NJPeRFN/cKaidAV1+so/ZBXOSw=,tag:ZaOvASxLMYpKxihwiBigog==,type:str]
  OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:et/vw+MqQQqnBb9eBuv9srdT4y2ePyKlny8Tw4zvYQ==,iv:RAhut9E/zoa2IULMRgEpd2ijzQbg7jqRzx9XsimRCo0=,tag:fD/SoU8T37/4VOhF/T1Mfw==,type:str]
  bookmarks.yaml: ENC[AES256_GCM,data:C3VxowJMsToWtByYmiwbrAr/FoZjS0KlzH1hnvyEB4rz+lxat07iFOYIey6PkBQ3SPkjfcaVhxd4nYBITz4W9fbUI3/H6k6Itg8L1gkTvGEYR0IAx6RlxRKdyAgP8iuwZC87p209MfUDLg6jBKM7YvanPAaUSqYh0tYi+sTusvp524HNIEkn0VvWYsIpAVSfPlkILsniwWZ9l/7/ozkKvWAM58AaKkz8YEplKqkvy7Rlx5r2chcyhQpNBETy8XA5+U+GCgSTzqwnVhOB0d1L+w3OvG4Js0hvl5xy8UOi7uBjHcZkcCdNUlidGhFlI1NQ0APcm14nYVBejSsexrhKkScfcqdR4uV+XKn2ryBcSkWrsBD6Ky+LOMsahCbVo+OCki/YK5FJ8EsHCJn1Z6JL1B7uREizt4fhyARAHlQndJVCRT7g0SlLZ7OqHymN2a5YcIR0atiBu/Ht0ZWG1zEY+HOc9LrwYuHoTjDql0oGaKF6KIQOI6wA5JLceBgLqV60FeWV1N19W+g6PDFSNYMS3f0kvJyJf4888vJpZI1XC5wr6KDLD38ChMHCMRzAuI0wN28HYx4+wmjk88cuax2u2f6a92/92weYLWMZ0X1ebXUf+13mnROU2N9vI5yuU24H3gmJbBkMpXNoI/R7NzFiF3rlRs0r4rUke9a+qITjOoM3e624hds/eCbsiv/hdY8Njb6N9jMIX7fReurHcV4XYPl7oWZKd0PUS4j4gCWTiKGqCzhR8UQxV/6lHNXIAOBmmJfoTJ+YnIwcSovDamDkqZZKC3PiO3/7tfqsJds228mNK61/XHspFiJU0hRfPWwtVWhzwhFkLyWq4A2sHOiIyaEWKkmfYUGcAmHbIU/oCoPxfcQVQNPghUVLRJwAtt0UdYoJWvyNqRGriuzGkasXkxv94srKlH7BebTnnlnGeujX4Dt2R6vPipX8fVMHiHfO8hosPOuQprXy58DXleN2ckRpeNIUBvjFJTO40Kg89yXgXLYjQjZZh6Wqx0jwlU6j8baMAt5x,iv:J+REbDBl0p98/D8VsjfAD72sYeXKS9xSIPFhxkpe9M8=,tag:8YeenqnIA5GYi/+ParOzCg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19nu7uf8dageqlmzk23x7vl24fpn0l7cq20l3l4xxf2sk2xd5h98qss437p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc1hyV3pxdVRvVTI0TEx5
        QXR0akcvWWUrdjBEWlU2ZXMxM2xOMTdhWEZ3Ckg2M3VIRFcvQUFxSDVyMHd6QWFp
        b3RWeG5RSVBrYWp1WVJTK0ZSeFFINjQKLS0tIHN3VG5qTUVpMkpKMW9WR2VqVHZ5
        L2tTZTZrK1U1N3NWK0dKM1NDTjB2Y2cK/Pi/9Rhd8lAueoplZOnZUguhnliFPpkn
        ccGD1S3bz459b4b4+0GqlZQBx2o3WJApsj5Oxuxkp4YwJoUIa04OPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-28T01:33:39Z"
  mac: ENC[AES256_GCM,data:hDvD9EuRjLC5VyewkdMCYRLHhhtHF9v+PeudNVqaO+0qScz1/NGqhBAPbHqj5oq7EMhVAdbevDJl1jmm3fjseJi15s45AIdmskLIA+hUzdcy8eZenpEfebjFgIPWqDLJDVbqcjLtgrCqXWbnWZdMyz/FvoPCjUAQeE28OuZhZGY=,iv:BJ7aOL2r+Mb4PFHtu+bmKGQF6Pgub8Foyn/zGwhcIMA=,tag:xugZkDi+hLDOldcIF60yDw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
