---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      qbittorrent:
        annotations:
          configmap.reloader.stakater.com/reload: qbittorrent-dnsdist
          secret.reloader.stakater.com/reload: qbittorrent-secret
        initContainers:
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-19
              tag: 1.9.10
            restartPolicy: Always
          gluetun:
            dependsOn:
              - dnsdist
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              DOT: "off"
              DNS_ADDRESS: "127.0.0.2"
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              WIREGUARD_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: ${CLUSTER_CIDR},${SERVICE_CIDR}
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            resources:
              limits:
                squat.ai/tun: "1"
            restartPolicy: Always
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
              capabilities:
                add:
                  - NET_ADMIN
        pod:
          #securityContext:
          # fsGroup: 2000
          # fsGroupChangePolicy: "OnRootMismatch"
          # supplementalGroups:
          #   - 3005
          terminationGracePeriodSeconds: 120
        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/liana64/qbittorrent
              tag: 5.1.2@sha256:8b32026f06a8922318d8c80c6b867aefc2b7373b31177de1c2d071c866be4a8c
            env:
              UMASK: "022"
              QBT_WEBUI_PORT: &port 8080
              QBT_TORRENTING_PORT: &torrentPort 61175
              QBT_BitTorrent__Session__MaxActiveDownloads: 10
              QBT_BitTorrent__Session__MaxActiveTorrents: 16384
              QBT_BitTorrent__Session__MaxActiveUploads: 50
              QBT_BitTorrent__Session__DefaultSavePath: "/media/downloads"
              QBT_Application__MemoryWorkingSetLimit:
                valueFrom:
                  resourceFieldRef:
                    containerName: qbittorrent
                    resource: limits.memory
                    divisor: 1Mi
              QBT_Preferences__WebUI__Username:
                valueFrom:
                  secretKeyRef:
                    name: qbittorrent-secret
                    key: QBITTORRENT_USER
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 150m
                memory: 1Gi
              limits:
                memory: 4Gi
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: 0.0.4@sha256:838ba41b3c736b23ae30f7e79a2610173f389a5ac6fb2b3e9c7bd482b9353c18
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_EXTERNAL_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/description: Torrent client
          gethomepage.dev/icon: qbittorrent
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: qbittorrent-tls
            hosts: [*host]
    persistence:
      config:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-forward:
              - path: /config
      media:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 600Gi
        retain: true
        advancedMounts:
          qbittorrent:
            app:
              - path: /media
      dnsdist:
        type: configMap
        name: qbittorrent-dnsdist
        advancedMounts:
          qbittorrent:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true
