# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: qbittorrent-secret
stringData:
  QBITTORRENT_USER: ENC[AES256_GCM,data:RLs5wdk=,iv:R5aH4R1sf7h7ZFdfivVyw2rSJXFFpyg12CgFdiIr0vU=,tag:joy0VqUbempaiC7c8oh0NA==,type:str]
  QBITTORRENT_PASS: ENC[AES256_GCM,data:31fMWugPVq9gv7jRHaNepwN8CK1JldqPRN1lUg==,iv:f28iPDdmRfHGfl7CDN9BzGgwCae0wCwr7Hvs+xr9aVY=,tag:bhpFVVyhbf4d4apsJkpm+w==,type:str]
  WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:GYiVcpLQzM2hbKcPeJw=,iv:hFvmCIeWVUJR1KbIxOZ9tDNJ2vb/j01hRrUVXEhOgjU=,tag:NyAqgzNbwTYYijbLsOFrFw==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Ta2x/908kEYB9IYPdNz89SheDbnYYy5FUz3QdE4Nmm0lOGBFPrWdn1Kvo5U=,iv:tC/QvsTJ0/48hz0BGOWRZyJ70sf6dVM/ssDi4Wc+pjI=,tag:xuzRGBjAvSuADlHe+LFMow==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:SRjuJAaO3lvZxaSJKGDa+PD76gGCJx/JzEh2ydnXWqOGC64ymK7ydHQ1u40=,iv:93ofKlCl7bq7LeDAdxrN6Fep9zzHk6TLtTSURI5qfak=,tag:tBFp6VXz/8UXLfmkR6KTBw==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:pnK59FN5UnORafw=,iv:zswBNxLhVLzijqNtL8naH0/c10eY8iLmtd2GhB50bsw=,tag:LrMmaIJcBosKSTeE2AW4rw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY2NmZWZWNVNwSHhnWFEr
        SWhtVGZibGZxS3RZbVAvZDJZYlBzSXNIRmtnCm01bG1TSWJ5dDUxMmloMVY2bjZh
        NldWUVJDZGREQ1pYTlhWaFVaVy9xUlUKLS0tIFUrTjkvS25yNXlFODlubk92SFBM
        a0h0Yld6VmVtckZKK2dzKzdxUDdVQkEKFKTC+9eORRMASEWkaPA1tu1olsxzTrgq
        4G8lSn65PkL1/+qztHunmpHUsSkyTrjAUziimAnh+N5Xk8NFSad0pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-04T02:38:02Z"
  mac: ENC[AES256_GCM,data:DbdtqBoUf/QbPEEMgc0fv0mq4VPwVVkZSBWUo0eDs6vVUH2XqfU9Yz+bNkIfERqDGlpN2ZqdmNE89qZ/O6d7PpyWaOyZwfcG6a07HOyJwj+GQHp6crArt+8CfEbjB6Tb4sQrjuFcPkFl/zeNJJm4XNXJdiqsVlWNPusp61gfg/c=,iv:k5jFiohL8ykvduFgNWA7oiQ2IU97sn5DmRODZ0I08xU=,tag:RjCtOzzdnBpBFYgA8qm/Ig==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
