---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app mautrix-signal
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: mautrix-signal-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: "mautrix-signal-configmap"
            items:
              - key: config.yaml
        - configMap:
            name: "mautrix-signal-configmap"
            items:
              - key: registration.yaml
  data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: "336bff2a-c389-4307-bacc-b3bf016ee8d6"
    - secretKey: MAUTRIX_SIGNAL_POSTGRES_USER
      remoteRef:
        key: "1874a5b5-3745-4e6b-82f6-b3c001624911"
    - secretKey: MAUTRIX_SIGNAL_POSTGRES_PASSWORD
      remoteRef:
        key: "3351a1b6-b322-4f4c-9e8b-b3c00162564a"
    - secretKey: MAUTRIX_SIGNAL_POSTGRES_DB
      remoteRef:
        key: "c35a029f-f83e-4329-ad84-b3c0016267fc"
    - secretKey: SIGNAL_AS_TOKEN
      remoteRef:
        key: "ab417a4f-007f-407d-ab74-b3c001638bf0"
    - secretKey: SIGNAL_HS_TOKEN
      remoteRef:
        key: "ab6ebc30-5c04-47e6-b725-b3c0016222bc"
    - secretKey: SIGNAL_SENDER_LOCAL_PART
      remoteRef:
        key: "9643ecbb-60b8-49e0-88a3-b3c001623138"
