---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mautrix-signal
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      mautrix-signal:
        labels:
          postgres: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/liana64/postgres-init
              tag: 16
            envFrom:
              - secretRef:
                  name: mautrix-signal-db-secret
        containers:
          app:
            image:
              repository: dock.mau.dev/mautrix/signal
              tag: v25.12@sha256:4a1cc8ce54a388a89f58e53cdd451e11f32fc416a8ae3699c9539c8d36f5ed52
            command: ["/usr/bin/mautrix-signal"]
            args: ["-c", "/data/config.yaml", "--no-update"]
            env:
              TZ: ${TIMEZONE}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8000
    ingress:
      app:
        className: traefik-external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_EXTERNAL_DOMAIN}"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-middleware-chain-synapse@kubernetescrd"
        hosts:
          - host: &host "mautrix-signal.${SECRET_EXTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: mautrix-signal-tls
            hosts: [*host]
    persistence:
      config:
        type: secret
        name: mautrix-signal-secret
        globalMounts:
          - path: /data/config.yaml
            subPath: config.yaml
            readOnly: true
          - path: /data/registration.yaml
            subPath: registration.yaml
            readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          mautrix-signal:
            app:
              - path: /tmp
                subPath: tmp
