# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mautrix-signal-db-secret
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:dY2uDOBkl2a5BtmTRWMgU6ZK3JxGyL51NSY2JBkCnwst9gINUcCJLA==,iv:QINMoj++bjCjlTfZ0cbfpQWOrT1gohjA7xHCqsLwiDM=,tag:3kkrK2f+HOr7iKqSSjyQrw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:rllZBxfDiPkH2+sJYEg=,iv:820/t8jznaVZ2AiJUpHeH/DlmhNp9MA3xmDE/nXiHqs=,tag:zbIY3+PUloKDWDFgbQSBuA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:VXRsLlsJMvBiz1BvEZA=,iv:jXY8gHT8JHLubrLrjte+gTl1vd0GJt17niyOem+cnM0=,tag:zpLmhZnSw0/Rf5ifO7hfIA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:6EL2OC0CkalJ06K3vMEaTMRA4QZxl8QDYNbkB16d28Cfa9Z9Wz/fpWT7rhYhPPKZqWIhxLLkWoo2NqCiwbSWQA==,iv:IAdsaPBMQHualaWVEUxzkEisKdPpr1Y5iwM0ZJhcOKk=,tag:moFFjL0DMTUbfpE0fzytAw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OH0Ckvm49kjY07CD+R+6jb6uzswN9v9Ea0XaHA==,iv:S2Lia2y9wUiCwei8CizNpckYKAvahu2KKAxu4JmSJJQ=,tag:JPPLd4vqreRNr77a7Kd8jw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUHNKNWtFd09PZFZ3amNk
        ckUydDhzQlZmczUvbVh1S3c3YkxwM3F1UzNBCmxaRGtvbG9CZzRUVmVCQVFOeXpm
        Q0VjMTJuK3BJTGdMUTB6N0FlekxMbmMKLS0tIFYvQXZQeDdJMDN2MWJnUzE5UEFW
        NHFQcm5yTGJWcnRPSW1nU2VGTWV6a2MKrJ+HRb63zn1QIV0I+WiCGd+fri/HFrh7
        sFerhvLJmcq308s+lyKyBnJw+OkL3HsgdZ0LP7cWNH6J7ZAM1hm5iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T21:38:57Z"
  mac: ENC[AES256_GCM,data:cnHRi/75DSX6bbtOeGpPdIuc/V0aQiQ0LUAvOhWJXKwZ5dly6N/UCZyg3BJwEZEdX8OFFSaeZGi5IcZLYzi0dXdbrmhQeUbiQ7//2pLsfKFpv66JfuxVMKXIFaHcS7Gy2uaOUDRJ6exZuQzo52gjbTgYnmpP1MS29vpuEWQK5Ts=,iv:SF7gUGp7XibOn5krQVxs4FWmnViqrVULV8gEpXYq1Kg=,tag:hR42XfBFvQPWe0YmFErcKQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
