---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app windmill
spec:
  interval: 30m
  chart:
    spec:
      chart: windmill
      version: 2.0.313
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    windmill:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          - name: init-db
            image: ghcr.io/onedr0p/postgres-init:16
            envFrom:
              - secretRef:
                  name: &secret windmill-secret
          - name: init-grants
            image: ghcr.io/onedr0p/postgres-init:16
            command:
              - /bin/bash
              - -c
              - |
                #!/bin/bash

                set -o errexit
                set -o nounset

                /var/run/grants.sh
            envFrom:
              - secretRef:
                  name: *secret
      baseDomain: &host "windmill.${SECRET_INTERNAL_DOMAIN}"
      baseProtocol: https
      appReplicas: 1
      lspReplicas: 1
      multiplayerReplicas: 1
      workerGroups:
        - name: default
          replicas: 2
          resources:
            requests:
              memory: 1028Mi
              cpu: 500m
            limits:
              memory: 2048Mi
        - name: native
          replicas: 1
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
    ingress:
      enabled: true
      className: traefik
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Windmill
        gethomepage.dev/group: Services
        gethomepage.dev/icon: webhook.png
        gethomepage.dev/href: https://windmill.${SECRET_INTERNAL_DOMAIN}
      tls:
        - secretName: windmill-tls
          hosts: [*host]
    postgresql:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: WINDMILL_POSTGRES_URL
      targetPath: windmill.databaseUrl
