---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app thelounge
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      thelounge:
        annotations:
          configmap.reloader.stakater.com/reload: irc-dnsdist
          secret.reloader.stakater.com/reload: irc-secret
        initContainers:
          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-19
              tag: 1.9.8
            restartPolicy: Always
          gluetun:
            dependsOn:
              - dnsdist
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              DOT: "off"
              DNS_ADDRESS: "127.0.0.2"
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              WIREGUARD_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: ${NODE_CIDR},${CLUSTER_CIDR},${SERVICE_CIDR}
            envFrom:
              - secretRef:
                  name: irc-secret
            resources:
              limits:
                squat.ai/tun: "1"
            restartPolicy: Always
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
              capabilities:
                add:
                  - NET_ADMIN
        containers:
          app:
            image:
              repository: ghcr.io/thelounge/thelounge
              tag: 4.4.3@sha256:8e0a075f7461aaa566cf552eef1d1586b29be9ca1e377ef61cb77461b2d16c6c
            env:
              THELOUNGE_HOME: /config
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            #            securityContext:
            #              runAsUser: 2000
            #              runAsGroup: 2000
            #              runAsNonRoot: true
            #              fsGroup: 2000
            #              allowPrivilegeEscalation: false
            #              readOnlyRootFilesystem: true
            #              capabilities:
            #                drop:
            #                  - ALL
    ingress:
      app:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Services
          gethomepage.dev/name: The Lounge
          gethomepage.dev/description: IRC client
          gethomepage.dev/icon: thelounge
        hosts:
          - host: &host "irc.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: thelounge-tls
            hosts: [*host]
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9000
    persistence:
      config:
        storageClass: cluster-nvme
        accessMode: ReadWriteOnce
        size: 256Mi
        retain: true
        globalMounts:
          - path: /config
      dnsdist:
        type: configMap
        name: irc-dnsdist
        advancedMounts:
          thelounge:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true
